package com.yc.utesdk.utils.open;

import com.yc.utesdk.log.LogUtils;

/* loaded from: classes4.dex */
public class DeviceLanguageType {
    public static final int BAND_LANGUAGE_AM = 31;
    public static final int BAND_LANGUAGE_AR = 10;
    public static final int BAND_LANGUAGE_AZ = 32;
    public static final int BAND_LANGUAGE_BE = 28;
    public static final int BAND_LANGUAGE_BG = 38;
    public static final int BAND_LANGUAGE_BN = 17;
    public static final int BAND_LANGUAGE_BS = 39;
    public static final int BAND_LANGUAGE_CA = 48;
    public static final int BAND_LANGUAGE_CEB = 79;
    public static final int BAND_LANGUAGE_CN = 1;
    public static final int BAND_LANGUAGE_CS = 22;
    public static final int BAND_LANGUAGE_DA = 57;
    public static final int BAND_LANGUAGE_DE = 5;
    public static final int BAND_LANGUAGE_EL = 90;
    public static final int BAND_LANGUAGE_EN = 2;
    public static final int BAND_LANGUAGE_EN_NZ = 112;
    public static final int BAND_LANGUAGE_ES = 6;
    public static final int BAND_LANGUAGE_ES_419 = 102;
    public static final int BAND_LANGUAGE_ES_AR = 107;
    public static final int BAND_LANGUAGE_ES_BR = 103;
    public static final int BAND_LANGUAGE_ES_PH = 106;
    public static final int BAND_LANGUAGE_ES_US = 105;
    public static final int BAND_LANGUAGE_ES_UY = 104;
    public static final int BAND_LANGUAGE_ET_EE = 111;
    public static final int BAND_LANGUAGE_EU = 37;
    public static final int BAND_LANGUAGE_FA = 40;
    public static final int BAND_LANGUAGE_FI = 98;
    public static final int BAND_LANGUAGE_FIL = 41;
    public static final int BAND_LANGUAGE_FR = 7;
    public static final int BAND_LANGUAGE_GA = 33;
    public static final int BAND_LANGUAGE_GU = 43;
    public static final int BAND_LANGUAGE_GV = 67;
    public static final int BAND_LANGUAGE_HA = 46;
    public static final int BAND_LANGUAGE_HI = 12;
    public static final int BAND_LANGUAGE_HK = 23;
    public static final int BAND_LANGUAGE_HR = 51;
    public static final int BAND_LANGUAGE_HT = 45;
    public static final int BAND_LANGUAGE_HU = 26;
    public static final int BAND_LANGUAGE_ID = 96;
    public static final int BAND_LANGUAGE_IG = 94;
    public static final int BAND_LANGUAGE_ILO = 95;
    public static final int BAND_LANGUAGE_IN = 19;
    public static final int BAND_LANGUAGE_IT = 8;
    public static final int BAND_LANGUAGE_IT_LT = 110;
    public static final int BAND_LANGUAGE_IW = 24;
    public static final int BAND_LANGUAGE_JA = 4;
    public static final int BAND_LANGUAGE_KK = 44;
    public static final int BAND_LANGUAGE_KM = 42;
    public static final int BAND_LANGUAGE_KN = 49;
    public static final int BAND_LANGUAGE_KO = 3;
    public static final int BAND_LANGUAGE_KU = 53;
    public static final int BAND_LANGUAGE_LA = 54;
    public static final int BAND_LANGUAGE_LB = 55;
    public static final int BAND_LANGUAGE_LV_LV = 109;
    public static final int BAND_LANGUAGE_MAI = 66;
    public static final int BAND_LANGUAGE_MG = 60;
    public static final int BAND_LANGUAGE_MK = 65;
    public static final int BAND_LANGUAGE_ML = 63;
    public static final int BAND_LANGUAGE_MN = 101;
    public static final int BAND_LANGUAGE_MR = 61;
    public static final int BAND_LANGUAGE_MS = 64;
    public static final int BAND_LANGUAGE_MY = 68;
    public static final int BAND_LANGUAGE_NAP = 69;
    public static final int BAND_LANGUAGE_NE = 70;
    public static final int BAND_LANGUAGE_NL = 15;
    public static final int BAND_LANGUAGE_NO = 71;
    public static final int BAND_LANGUAGE_NY = 73;
    public static final int BAND_LANGUAGE_OC = 34;
    public static final int BAND_LANGUAGE_OM = 36;
    public static final int BAND_LANGUAGE_OR = 35;
    public static final int BAND_LANGUAGE_PA = 20;
    public static final int BAND_LANGUAGE_PL = 13;
    public static final int BAND_LANGUAGE_PS = 72;
    public static final int BAND_LANGUAGE_PT = 9;
    public static final int BAND_LANGUAGE_QU = 52;
    public static final int BAND_LANGUAGE_RM = 59;
    public static final int BAND_LANGUAGE_RO = 27;
    public static final int BAND_LANGUAGE_RU = 14;
    public static final int BAND_LANGUAGE_RU_BY = 108;
    public static final int BAND_LANGUAGE_RW = 56;
    public static final int BAND_LANGUAGE_SD = 91;
    public static final int BAND_LANGUAGE_SI = 76;
    public static final int BAND_LANGUAGE_SK = 25;
    public static final int BAND_LANGUAGE_SL = 77;
    public static final int BAND_LANGUAGE_SM = 81;
    public static final int BAND_LANGUAGE_SO = 80;
    public static final int BAND_LANGUAGE_SQ = 29;
    public static final int BAND_LANGUAGE_SR = 75;
    public static final int BAND_LANGUAGE_SV = 74;
    public static final int BAND_LANGUAGE_SW = 78;
    public static final int BAND_LANGUAGE_SYR = 93;
    public static final int BAND_LANGUAGE_TA = 85;
    public static final int BAND_LANGUAGE_TE = 84;
    public static final int BAND_LANGUAGE_TG = 83;
    public static final int BAND_LANGUAGE_TH = 21;
    public static final int BAND_LANGUAGE_TI = 86;
    public static final int BAND_LANGUAGE_TK = 87;
    public static final int BAND_LANGUAGE_TL = 82;
    public static final int BAND_LANGUAGE_TR = 16;
    public static final int BAND_LANGUAGE_UK = 88;
    public static final int BAND_LANGUAGE_UR = 18;
    public static final int BAND_LANGUAGE_UZ = 89;
    public static final int BAND_LANGUAGE_VI = 99;
    public static final int BAND_LANGUAGE_XH = 50;
    public static final int BAND_LANGUAGE_YO = 97;
    public static final int BAND_LANGUAGE_ZU = 100;
    public static final int IS_DISPLAY_BAND_LANGUAGE_AM = 64;
    public static final int IS_DISPLAY_BAND_LANGUAGE_AR = 512;
    public static final int IS_DISPLAY_BAND_LANGUAGE_AZ = 128;
    public static final int IS_DISPLAY_BAND_LANGUAGE_BE = 8;
    public static final int IS_DISPLAY_BAND_LANGUAGE_BG = 8192;
    public static final int IS_DISPLAY_BAND_LANGUAGE_BN = 65536;
    public static final int IS_DISPLAY_BAND_LANGUAGE_BS = 16384;
    public static final int IS_DISPLAY_BAND_LANGUAGE_CA = 8388608;
    public static final int IS_DISPLAY_BAND_LANGUAGE_CEB = 64;
    public static final int IS_DISPLAY_BAND_LANGUAGE_CN = 1;
    public static final int IS_DISPLAY_BAND_LANGUAGE_CS = 2097152;
    public static final int IS_DISPLAY_BAND_LANGUAGE_DA = 256;
    public static final int IS_DISPLAY_BAND_LANGUAGE_DE = 16;
    public static final int IS_DISPLAY_BAND_LANGUAGE_EL = 131072;
    public static final int IS_DISPLAY_BAND_LANGUAGE_EN = 2;
    public static final int IS_DISPLAY_BAND_LANGUAGE_EN_NZ = 32768;
    public static final int IS_DISPLAY_BAND_LANGUAGE_ES = 32;
    public static final int IS_DISPLAY_BAND_LANGUAGE_ES_419 = 32;
    public static final int IS_DISPLAY_BAND_LANGUAGE_ES_AR = 1024;
    public static final int IS_DISPLAY_BAND_LANGUAGE_ES_BR = 64;
    public static final int IS_DISPLAY_BAND_LANGUAGE_ES_PH = 512;
    public static final int IS_DISPLAY_BAND_LANGUAGE_ES_US = 256;
    public static final int IS_DISPLAY_BAND_LANGUAGE_ES_UY = 128;
    public static final int IS_DISPLAY_BAND_LANGUAGE_ET_EE = 16384;
    public static final int IS_DISPLAY_BAND_LANGUAGE_EU = 4096;
    public static final int IS_DISPLAY_BAND_LANGUAGE_FA = 32768;
    public static final int IS_DISPLAY_BAND_LANGUAGE_FI = 2;
    public static final int IS_DISPLAY_BAND_LANGUAGE_FIL = 65536;
    public static final int IS_DISPLAY_BAND_LANGUAGE_FR = 64;
    public static final int IS_DISPLAY_BAND_LANGUAGE_GA = 256;
    public static final int IS_DISPLAY_BAND_LANGUAGE_GU = 262144;
    public static final int IS_DISPLAY_BAND_LANGUAGE_GV = 262144;
    public static final int IS_DISPLAY_BAND_LANGUAGE_HA = 2097152;
    public static final int IS_DISPLAY_BAND_LANGUAGE_HK = 4194304;
    public static final int IS_DISPLAY_BAND_LANGUAGE_HR = 4;
    public static final int IS_DISPLAY_BAND_LANGUAGE_HT = 1048576;
    public static final int IS_DISPLAY_BAND_LANGUAGE_HU = 2;
    public static final int IS_DISPLAY_BAND_LANGUAGE_ID = 8388608;
    public static final int IS_DISPLAY_BAND_LANGUAGE_IG = 2097152;
    public static final int IS_DISPLAY_BAND_LANGUAGE_ILO = 4194304;
    public static final int IS_DISPLAY_BAND_LANGUAGE_IN = 262144;
    public static final int IS_DISPLAY_BAND_LANGUAGE_IN_HI = 2048;
    public static final int IS_DISPLAY_BAND_LANGUAGE_IT = 128;
    public static final int IS_DISPLAY_BAND_LANGUAGE_IT_LT = 8192;
    public static final int IS_DISPLAY_BAND_LANGUAGE_IW = 8388608;
    public static final int IS_DISPLAY_BAND_LANGUAGE_JA = 8;
    public static final int IS_DISPLAY_BAND_LANGUAGE_KK = 524288;
    public static final int IS_DISPLAY_BAND_LANGUAGE_KM = 131072;
    public static final int IS_DISPLAY_BAND_LANGUAGE_KN = 1;
    public static final int IS_DISPLAY_BAND_LANGUAGE_KO = 4;
    public static final int IS_DISPLAY_BAND_LANGUAGE_KU = 16;
    public static final int IS_DISPLAY_BAND_LANGUAGE_LA = 32;
    public static final int IS_DISPLAY_BAND_LANGUAGE_LB = 64;
    public static final int IS_DISPLAY_BAND_LANGUAGE_LV_LV = 4096;
    public static final int IS_DISPLAY_BAND_LANGUAGE_MAI = 131072;
    public static final int IS_DISPLAY_BAND_LANGUAGE_MG = 2048;
    public static final int IS_DISPLAY_BAND_LANGUAGE_MK = 65536;
    public static final int IS_DISPLAY_BAND_LANGUAGE_ML = 16384;
    public static final int IS_DISPLAY_BAND_LANGUAGE_MN = 16;
    public static final int IS_DISPLAY_BAND_LANGUAGE_MR = 4096;
    public static final int IS_DISPLAY_BAND_LANGUAGE_MS = 32768;
    public static final int IS_DISPLAY_BAND_LANGUAGE_MY = 524288;
    public static final int IS_DISPLAY_BAND_LANGUAGE_NAP = 1048576;
    public static final int IS_DISPLAY_BAND_LANGUAGE_NE = 2097152;
    public static final int IS_DISPLAY_BAND_LANGUAGE_NL = 16384;
    public static final int IS_DISPLAY_BAND_LANGUAGE_NO = 4194304;
    public static final int IS_DISPLAY_BAND_LANGUAGE_NY = 1;
    public static final int IS_DISPLAY_BAND_LANGUAGE_OC = 512;
    public static final int IS_DISPLAY_BAND_LANGUAGE_OM = 2048;
    public static final int IS_DISPLAY_BAND_LANGUAGE_OR = 1024;
    public static final int IS_DISPLAY_BAND_LANGUAGE_PA = 524288;
    public static final int IS_DISPLAY_BAND_LANGUAGE_PL = 4096;
    public static final int IS_DISPLAY_BAND_LANGUAGE_PS = 8388608;
    public static final int IS_DISPLAY_BAND_LANGUAGE_PT = 256;
    public static final int IS_DISPLAY_BAND_LANGUAGE_QU = 8;
    public static final int IS_DISPLAY_BAND_LANGUAGE_RM = 1024;
    public static final int IS_DISPLAY_BAND_LANGUAGE_RO = 4;
    public static final int IS_DISPLAY_BAND_LANGUAGE_RU = 8192;
    public static final int IS_DISPLAY_BAND_LANGUAGE_RU_BY = 2048;
    public static final int IS_DISPLAY_BAND_LANGUAGE_RW = 128;
    public static final int IS_DISPLAY_BAND_LANGUAGE_SD = 262144;
    public static final int IS_DISPLAY_BAND_LANGUAGE_SI = 8;
    public static final int IS_DISPLAY_BAND_LANGUAGE_SK = 1;
    public static final int IS_DISPLAY_BAND_LANGUAGE_SL = 16;
    public static final int IS_DISPLAY_BAND_LANGUAGE_SM = 256;
    public static final int IS_DISPLAY_BAND_LANGUAGE_SO = 128;
    public static final int IS_DISPLAY_BAND_LANGUAGE_SQ = 16;
    public static final int IS_DISPLAY_BAND_LANGUAGE_SR = 4;
    public static final int IS_DISPLAY_BAND_LANGUAGE_SV = 2;
    public static final int IS_DISPLAY_BAND_LANGUAGE_SW = 32;
    public static final int IS_DISPLAY_BAND_LANGUAGE_SYR = 1048576;
    public static final int IS_DISPLAY_BAND_LANGUAGE_TA = 4096;
    public static final int IS_DISPLAY_BAND_LANGUAGE_TE = 2048;
    public static final int IS_DISPLAY_BAND_LANGUAGE_TG = 1024;
    public static final int IS_DISPLAY_BAND_LANGUAGE_TH = 1048576;
    public static final int IS_DISPLAY_BAND_LANGUAGE_TI = 8192;
    public static final int IS_DISPLAY_BAND_LANGUAGE_TK = 16384;
    public static final int IS_DISPLAY_BAND_LANGUAGE_TL = 512;
    public static final int IS_DISPLAY_BAND_LANGUAGE_TR = 32768;
    public static final int IS_DISPLAY_BAND_LANGUAGE_UK = 32768;
    public static final int IS_DISPLAY_BAND_LANGUAGE_UR = 131072;
    public static final int IS_DISPLAY_BAND_LANGUAGE_UZ = 65536;
    public static final int IS_DISPLAY_BAND_LANGUAGE_VI = 4;
    public static final int IS_DISPLAY_BAND_LANGUAGE_XH = 2;
    public static final int IS_DISPLAY_BAND_LANGUAGE_YO = 1;
    public static final int IS_DISPLAY_BAND_LANGUAGE_ZU = 8;

    public static boolean isBandLanguageDisplay1(int i2) {
        int bandLanguageDisplay1 = SPUtil.getInstance().getBandLanguageDisplay1();
        boolean z2 = (bandLanguageDisplay1 & i2) == i2;
        LogUtils.d("isBandLanguageDisplay", "isSupport1 =" + z2 + ",functionType =" + i2 + ",function=" + bandLanguageDisplay1);
        return z2;
    }

    public static boolean isBandLanguageDisplay2(int i2) {
        int bandLanguageDisplay2 = SPUtil.getInstance().getBandLanguageDisplay2();
        boolean z2 = (bandLanguageDisplay2 & i2) == i2;
        LogUtils.d("isBandLanguageDisplay", "isSupport2 =" + z2 + ",functionType =" + i2 + ",function=" + bandLanguageDisplay2);
        return z2;
    }

    public static boolean isBandLanguageDisplay3(int i2) {
        int bandLanguageDisplay3 = SPUtil.getInstance().getBandLanguageDisplay3();
        boolean z2 = (bandLanguageDisplay3 & i2) == i2;
        LogUtils.d("isBandLanguageDisplay", "isSupport3 =" + z2 + ",functionType =" + i2 + ",function=" + bandLanguageDisplay3);
        return z2;
    }

    public static boolean isBandLanguageDisplay4(int i2) {
        int bandLanguageDisplay4 = SPUtil.getInstance().getBandLanguageDisplay4();
        boolean z2 = (bandLanguageDisplay4 & i2) == i2;
        LogUtils.d("isBandLanguageDisplay", "isSupport4 =" + z2 + ",functionType =" + i2 + ",function=" + bandLanguageDisplay4);
        return z2;
    }

    public static boolean isBandLanguageDisplay5(int i2) {
        int bandLanguageDisplay5 = SPUtil.getInstance().getBandLanguageDisplay5();
        boolean z2 = (bandLanguageDisplay5 & i2) == i2;
        LogUtils.d("isBandLanguageDisplay", "isSupport5 =" + z2 + ",functionType =" + i2 + ",function=" + bandLanguageDisplay5);
        return z2;
    }
}
