package meshprovisioner.utils;

import aisble.error.GattError;
import android.util.SparseArray;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.app.FrameMetricsAggregator;
import androidx.media3.exoplayer.RendererCapabilities;
import androidx.media3.exoplayer.analytics.AnalyticsListener;
import androidx.media3.exoplayer.rtsp.RtspMessageChannel;
import androidx.media3.exoplayer.trackselection.AdaptiveTrackSelection;
import com.alibaba.sdk.android.openaccount.message.MessageConstants;
import com.alibaba.sdk.android.openaccount.ui.message.UIMessageConstants;
import com.aliyun.alink.business.devicecenter.config.genie.smartconfig.constants.DeviceCommonConstants;
import com.aliyun.alink.linksdk.tmp.utils.ErrorCode;
import com.facebook.internal.FacebookRequestErrorClassification;
import com.google.android.gms.common.ConnectionResult;
import com.google.zxing.pdf417.PDF417Common;
import com.luck.picture.lib.config.Crop;
import com.luck.picture.lib.config.PictureConfig;
import com.taobao.accs.antibrush.AntiBrush;
import com.taobao.accs.common.Constants;
import com.vivo.push.BuildConfig;
import com.xiaomi.infra.galaxy.fds.Common;
import com.yc.utesdk.ble.close.KeyType;
import com.yc.utesdk.listener.AIWatchListener;
import io.flutter.plugin.platform.PlatformPlugin;
import javax.jmdns.impl.constants.DNSConstants;
import org.joda.time.DateTimeConstants;

/* loaded from: classes5.dex */
public class CompanyIdentifiers {
    public static final SparseArray<String> vendorModels = new SparseArray<>();

    static {
        initVendorModels();
    }

    public static String getCompanyName(short s2) {
        String str = vendorModels.get(s2);
        return str == null ? "Company ID unavailable" : str;
    }

    public static void initVendorModels() {
        SparseArray<String> sparseArray = vendorModels;
        sparseArray.append(0, "Ericsson Technology Licensing");
        sparseArray.append(1, "Nokia Mobile Phones");
        sparseArray.append(2, "Intel Corp.");
        sparseArray.append(3, "IBM Corp.");
        sparseArray.append(4, "Toshiba Corp.");
        sparseArray.append(5, "3Com");
        sparseArray.append(6, "Microsoft");
        sparseArray.append(7, "Lucent");
        sparseArray.append(8, "Motorola");
        sparseArray.append(9, "Infineon Technologies AG");
        sparseArray.append(10, "Cambridge Silicon Radio");
        sparseArray.append(11, "Silicon Wave");
        sparseArray.append(12, "Digianswer A/S");
        sparseArray.append(13, "Texas Instruments Inc.");
        sparseArray.append(14, "Parthus Technologies Inc.");
        sparseArray.append(15, "Broadcom Corporation");
        sparseArray.append(16, "Mitel Semiconductor");
        sparseArray.append(17, "Widcomm, Inc.");
        sparseArray.append(18, "Zeevo, Inc.");
        sparseArray.append(19, "Atmel Corporation");
        sparseArray.append(20, "Mitsubishi Electric Corporation");
        sparseArray.append(21, "RTX Telecom A/S");
        sparseArray.append(22, "KC Technology Inc.");
        sparseArray.append(23, "Newlogic");
        sparseArray.append(24, "Transilica, Inc.");
        sparseArray.append(25, "Rohde & Schwarz GmbH & Co. KG");
        sparseArray.append(26, "TTPCom Limited");
        sparseArray.append(27, "Signia Technologies, Inc.");
        sparseArray.append(28, "Conexant Systems Inc.");
        sparseArray.append(29, "Qualcomm");
        sparseArray.append(30, "Inventel");
        sparseArray.append(31, "AVM Berlin");
        sparseArray.append(32, "BandSpeed, Inc.");
        sparseArray.append(33, "Mansella Ltd");
        sparseArray.append(34, "NEC Corporation");
        sparseArray.append(35, "WavePlus Technology Co.,Ltd.");
        sparseArray.append(36, "Alcatel");
        sparseArray.append(37, "NXP Semiconductors (formerly Philips Semiconductors);");
        sparseArray.append(38, "C Technologies");
        sparseArray.append(39, "Open Interface");
        sparseArray.append(40, "R F Micro Devices");
        sparseArray.append(41, "Hitachi Ltd");
        sparseArray.append(42, "Symbol Technologies, Inc.");
        sparseArray.append(43, "Tenovis");
        sparseArray.append(44, "Macronix International Co. Ltd.");
        sparseArray.append(45, "GCT Semiconductor");
        sparseArray.append(46, "Norwood Systems");
        sparseArray.append(47, "MewTel Technology Inc.");
        sparseArray.append(48, "ST Microelectronics");
        sparseArray.append(49, "Synopsys, Inc.");
        sparseArray.append(50, "Red-M (Communications,Ltd");
        sparseArray.append(51, "Commil Ltd");
        sparseArray.append(52, "Computer Access Technology Corporation (CATC);");
        sparseArray.append(53, "Eclipse (HQ Espana,S.L.");
        sparseArray.append(54, "Renesas Electronics Corporation");
        sparseArray.append(55, "Mobilian Corporation");
        sparseArray.append(56, "Syntronix Corporation");
        sparseArray.append(57, "Integrated System Solution Corp.");
        sparseArray.append(58, "Matsushita Electric Industrial Co.,Ltd.");
        sparseArray.append(59, "Gennum Corporation");
        sparseArray.append(60, "BlackBerry Limited (formerly Research In Motion);");
        sparseArray.append(61, "IPextreme, Inc.");
        sparseArray.append(62, "Systems and Chips, Inc");
        sparseArray.append(63, "Bluetooth SIG, Inc");
        sparseArray.append(64, "Seiko Epson Corporation");
        sparseArray.append(65, "Integrated Silicon Solution Taiwan, Inc.");
        sparseArray.append(66, "CONWISE Technology Corporation Ltd");
        sparseArray.append(67, "PARROT AUTOMOTIVE SAS");
        sparseArray.append(68, "Socket Mobile");
        sparseArray.append(69, "Atheros Communications, Inc.");
        sparseArray.append(70, "MediaTek, Inc.");
        sparseArray.append(71, "Bluegiga");
        sparseArray.append(72, "Marvell Technology Group Ltd.");
        sparseArray.append(73, "3DSP Corporation");
        sparseArray.append(74, "Accel Semiconductor Ltd.");
        sparseArray.append(75, "Continental Automotive Systems");
        sparseArray.append(76, "Apple, Inc.");
        sparseArray.append(77, "Staccato Communications, Inc.");
        sparseArray.append(78, "Avago Technologies");
        sparseArray.append(79, "APT Ltd.");
        sparseArray.append(80, "SiRF Technology, Inc.");
        sparseArray.append(81, "Tzero Technologies, Inc.");
        sparseArray.append(82, "J&M Corporation");
        sparseArray.append(83, "Free2move AB");
        sparseArray.append(84, "3DiJoy Corporation");
        sparseArray.append(85, "Plantronics, Inc.");
        sparseArray.append(86, "Sony Ericsson Mobile Communications");
        sparseArray.append(87, "Harman International Industries, Inc.");
        sparseArray.append(88, "Vizio, Inc.");
        sparseArray.append(89, "Nordic Semiconductor ASA");
        sparseArray.append(90, "EM Microelectronic-Marin SA");
        sparseArray.append(91, "Ralink Technology Corporation");
        sparseArray.append(92, "Belkin International, Inc.");
        sparseArray.append(93, "Realtek Semiconductor Corporation");
        sparseArray.append(94, "Stonestreet One,LLC");
        sparseArray.append(95, "Wicentric, Inc.");
        sparseArray.append(96, "RivieraWaves S.A.S");
        sparseArray.append(97, "RDA Microelectronics");
        sparseArray.append(98, "Gibson Guitars");
        sparseArray.append(99, "MiCommand Inc.");
        sparseArray.append(100, "Band XI International,LLC");
        sparseArray.append(101, "Hewlett-Packard Company");
        sparseArray.append(102, "9Solutions Oy");
        sparseArray.append(103, "GN Netcom A/S");
        sparseArray.append(104, "General Motors");
        sparseArray.append(105, "A&D Engineering, Inc.");
        sparseArray.append(106, "MindTree Ltd.");
        sparseArray.append(107, "Polar Electro OY");
        sparseArray.append(108, "Beautiful Enterprise Co.,Ltd.");
        sparseArray.append(109, "BriarTek, Inc");
        sparseArray.append(110, "Summit Data Communications, Inc.");
        sparseArray.append(111, "Sound ID");
        sparseArray.append(112, "Monster,LLC");
        sparseArray.append(113, "connectBlue AB");
        sparseArray.append(114, "ShangHai Super Smart Electronics Co. Ltd.");
        sparseArray.append(115, "Group Sense Ltd.");
        sparseArray.append(116, "Zomm,LLC");
        sparseArray.append(117, "Samsung Electronics Co. Ltd.");
        sparseArray.append(118, "Creative Technology Ltd.");
        sparseArray.append(119, "Laird Technologies");
        sparseArray.append(120, "Nike, Inc.");
        sparseArray.append(121, "lesswire AG");
        sparseArray.append(122, "MStar Semiconductor, Inc.");
        sparseArray.append(123, "Hanlynn Technologies");
        sparseArray.append(124, "A & R Cambridge");
        sparseArray.append(125, "Seers Technology Co.,Ltd.");
        sparseArray.append(126, "Sports Tracking Technologies Ltd.");
        sparseArray.append(127, "Autonet Mobile");
        sparseArray.append(128, "DeLorme Publishing Company, Inc.");
        sparseArray.append(129, "WuXi Vimicro");
        sparseArray.append(130, "Sennheiser Communications A/S");
        sparseArray.append(131, "TimeKeeping Systems, Inc.");
        sparseArray.append(132, "Ludus Helsinki Ltd.");
        sparseArray.append(133, "BlueRadios, Inc.");
        sparseArray.append(134, "Equinux AG");
        sparseArray.append(135, "Garmin International, Inc.");
        sparseArray.append(136, "Ecotest");
        sparseArray.append(137, "GN ReSound A/S");
        sparseArray.append(138, "Jawbone");
        sparseArray.append(139, "Topcon Positioning Systems,LLC");
        sparseArray.append(140, "Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions, Inc.);");
        sparseArray.append(141, "Zscan Software");
        sparseArray.append(142, "Quintic Corp");
        sparseArray.append(143, "Telit Wireless Solutions GmbH (formerly Stollmann E+V GmbH);");
        sparseArray.append(144, "Funai Electric Co.,Ltd.");
        sparseArray.append(145, "Advanced PANMOBIL systems GmbH & Co. KG");
        sparseArray.append(146, "ThinkOptics, Inc.");
        sparseArray.append(147, "Universal Electronics, Inc.");
        sparseArray.append(148, "Airoha Technology Corp.");
        sparseArray.append(149, "NEC Lighting,Ltd.");
        sparseArray.append(150, "ODM Technology, Inc.");
        sparseArray.append(151, "ConnecteDevice Ltd.");
        sparseArray.append(152, "zero1.tv GmbH");
        sparseArray.append(153, "i.Tech Dynamic Global Distribution Ltd.");
        sparseArray.append(154, "Alpwise");
        sparseArray.append(155, "Jiangsu Toppower Automotive Electronics Co.,Ltd.");
        sparseArray.append(156, "Colorfy, Inc.");
        sparseArray.append(157, "Geoforce Inc.");
        sparseArray.append(158, "Bose Corporation");
        sparseArray.append(159, "Suunto Oy");
        sparseArray.append(160, "Kensington Computer Products Group");
        sparseArray.append(161, "SR-Medizinelektronik");
        sparseArray.append(162, "Vertu Corporation Limited");
        sparseArray.append(163, "Meta Watch Ltd.");
        sparseArray.append(164, "LINAK A/S");
        sparseArray.append(165, "OTL Dynamics LLC");
        sparseArray.append(166, "Panda Ocean Inc.");
        sparseArray.append(167, "Visteon Corporation");
        sparseArray.append(168, "ARP Devices Limited");
        sparseArray.append(169, "Magneti Marelli S.p.A");
        sparseArray.append(170, "CAEN RFID srl");
        sparseArray.append(171, "Ingenieur-Systemgruppe Zahn GmbH");
        sparseArray.append(172, "Green Throttle Games");
        sparseArray.append(173, "Peter Systemtechnik GmbH");
        sparseArray.append(174, "Omegawave Oy");
        sparseArray.append(175, "Cinetix");
        sparseArray.append(176, "Passif Semiconductor Corp");
        sparseArray.append(177, "Saris Cycling Group, Inc");
        sparseArray.append(178, "Bekey A/S");
        sparseArray.append(179, "Clarinox Technologies Pty. Ltd.");
        sparseArray.append(180, "BDE Technology Co.,Ltd.");
        sparseArray.append(181, "Swirl Networks");
        sparseArray.append(182, "Meso international");
        sparseArray.append(183, "TreLab Ltd");
        sparseArray.append(184, "Qualcomm Innovation Center, Inc. (QuIC);");
        sparseArray.append(185, "Johnson Controls, Inc.");
        sparseArray.append(186, "Starkey Laboratories Inc.");
        sparseArray.append(187, "S-Power Electronics Limited");
        sparseArray.append(188, "Ace Sensor Inc");
        sparseArray.append(189, "Aplix Corporation");
        sparseArray.append(190, "AAMP of America");
        sparseArray.append(191, "Stalmart Technology Limited");
        sparseArray.append(192, "AMICCOM Electronics Corporation");
        sparseArray.append(193, "Shenzhen Excelsecu Data Technology Co.);Ltd");
        sparseArray.append(194, "Geneq Inc.");
        sparseArray.append(195, "adidas AG");
        sparseArray.append(196, "LG Electronics");
        sparseArray.append(197, "Onset Computer Corporation");
        sparseArray.append(198, "Selfly BV");
        sparseArray.append(199, "Quuppa Oy.");
        sparseArray.append(200, "GeLo Inc");
        sparseArray.append(201, "Evluma");
        sparseArray.append(202, "MC10");
        sparseArray.append(203, "Binauric SE");
        sparseArray.append(204, "Beats Electronics");
        sparseArray.append(205, "Microchip Technology Inc.");
        sparseArray.append(206, "Elgato Systems GmbH");
        sparseArray.append(207, "ARCHOS SA");
        sparseArray.append(208, "Dexcom, Inc.");
        sparseArray.append(209, "Polar Electro Europe B.V.");
        sparseArray.append(210, "Dialog Semiconductor B.V.");
        sparseArray.append(211, "Taixingbang Technology (HK,Co);. LTD.");
        sparseArray.append(212, "Kawantech");
        sparseArray.append(213, "Austco Communication Systems");
        sparseArray.append(214, "Timex Group USA, Inc.");
        sparseArray.append(215, "Qualcomm Technologies, Inc.");
        sparseArray.append(216, "Qualcomm Connected Experiences, Inc.");
        sparseArray.append(217, "Voyetra Turtle Beach");
        sparseArray.append(218, "txtr GmbH");
        sparseArray.append(219, "Biosentronics");
        sparseArray.append(220, "Procter & Gamble");
        sparseArray.append(221, "Hosiden Corporation");
        sparseArray.append(222, "Muzik LLC");
        sparseArray.append(223, "Misfit Wearables Corp");
        sparseArray.append(224, "Google");
        sparseArray.append(225, "Danlers Ltd");
        sparseArray.append(226, "Semilink Inc");
        sparseArray.append(227, "inMusic Brands, Inc");
        sparseArray.append(228, "L.S. Research Inc.");
        sparseArray.append(229, "Eden Software Consultants Ltd.");
        sparseArray.append(230, "Freshtemp");
        sparseArray.append(231, "KS Technologies");
        sparseArray.append(232, "ACTS Technologies");
        sparseArray.append(233, "Vtrack Systems");
        sparseArray.append(234, "Nielsen-Kellerman Company");
        sparseArray.append(235, "Server Technology Inc.");
        sparseArray.append(236, "BioResearch Associates");
        sparseArray.append(237, "Jolly Logic,LLC");
        sparseArray.append(238, "Above Average Outcomes, Inc.");
        sparseArray.append(239, "Bitsplitters GmbH");
        sparseArray.append(240, "PayPal, Inc.");
        sparseArray.append(241, "Witron Technology Limited");
        sparseArray.append(242, "Morse Project Inc.");
        sparseArray.append(243, "Kent Displays Inc.");
        sparseArray.append(244, "Nautilus Inc.");
        sparseArray.append(245, "Smartifier Oy");
        sparseArray.append(246, "Elcometer Limited");
        sparseArray.append(247, "VSN Technologies, Inc.");
        sparseArray.append(KeyType.SET_COMMON_RATE_TEST_INTERVAL, "AceUni Corp.,Ltd.");
        sparseArray.append(249, "StickNFind");
        sparseArray.append(250, "Crystal Code AB");
        sparseArray.append(251, "KOUKAAM a.s.");
        sparseArray.append(252, "Delphi Corporation");
        sparseArray.append(GattError.GATT_CCCD_CFG_ERROR, "ValenceTech Limited");
        sparseArray.append(254, "Stanley Black and Decker");
        sparseArray.append(255, "Typo Products,LLC");
        sparseArray.append(256, "TomTom International BV");
        sparseArray.append(257, "Fugoo, Inc.");
        sparseArray.append(258, "Keiser Corporation");
        sparseArray.append(259, "Bang & Olufsen A/S");
        sparseArray.append(KeyType.QUERY_FRK_DEVICE_CHIP_TYPE_COMMAND, "PLUS Location Systems Pty Ltd");
        sparseArray.append(KeyType.QUERY_FRK_DEVICE_BASE_ADDRESS_COMMAND, "Ubiquitous Computing Technology Corporation");
        sparseArray.append(KeyType.QUERY_FRK_DEVICE_ERASE_COMMAND, "Innovative Yachtter Solutions");
        sparseArray.append(KeyType.QUERY_FRK_DEVICE_WRITE_COMMAND, "William Demant Holding A/S");
        sparseArray.append(KeyType.SEND_MESSAGE_REPLY_DATA_COMMAND, "Chicony Electronics Co.,Ltd.");
        sparseArray.append(KeyType.QUERY_SEDENTARY_REMIND, "Atus BV");
        sparseArray.append(KeyType.QUERY_DRINK_WATER_REMIND, "Codegate Ltd");
        sparseArray.append(KeyType.QUERY_DO_NOT_DISTURB, "ERi, Inc");
        sparseArray.append(KeyType.QUERY_SOS_CONTACT, "Transducers Direct,LLC");
        sparseArray.append(KeyType.SET_BRIGHT_SCREEN_PARAM, "Fujitsu Ten LImited");
        sparseArray.append(KeyType.QUERY_BRIGHT_SCREEN_PARAM, "Audi AG");
        sparseArray.append(KeyType.QUERY_HEART_RATE_PARAM, "HiSilicon Technologies Col,Ltd.");
        sparseArray.append(KeyType.SEND_MENSTRUAL_START_DAY, "Nippon Seiki Co.,Ltd.");
        sparseArray.append(273, "Steelseries ApS");
        sparseArray.append(KeyType.QUERY_MENSTRUAL_DATA_FOR_MONTH, "Visybl Inc.");
        sparseArray.append(KeyType.ABORT_DIAL_BIN, "Openbrain Technologies,Co.,Ltd.");
        sparseArray.append(276, "Xensr");
        sparseArray.append(KeyType.SET_AI_WATCH_STATUS, "e.solutions");
        sparseArray.append(KeyType.SET_AI_WATCH_ENABLE, "10AK Technologies");
        sparseArray.append(KeyType.QUERY_AI_WATCH_ENABLE, "Wimoto Technologies Inc");
        sparseArray.append(KeyType.SET_AI_WATCH_VOICE_CONTENT, "Radius Networks, Inc.");
        sparseArray.append(KeyType.SET_CHAT_GPT_LANGUAGE_ENVIRONMENT, "Wize Technology Co.,Ltd.");
        sparseArray.append(KeyType.SET_AI_AGENT_TYPE, "Qualcomm Labs, Inc.");
        sparseArray.append(KeyType.SYNC_AI_AGENT_MEMO_TO_DEVICE, "Hewlett Packard Enterprise");
        sparseArray.append(KeyType.SET_LARGE_MODE_TYPE, "Baidu");
        sparseArray.append(KeyType.QUERY_IMAGE_WATCH_FACE_PARAMS, "Arendi AG");
        sparseArray.append(KeyType.SET_IMAGE_WATCH_FACE_CONFIG_RK, "Skoda Auto a.s.");
        sparseArray.append(KeyType.SWITCH_WATCH_FACE_RK, "Volkswagen AG");
        sparseArray.append(288, "Porsche AG");
        sparseArray.append(289, "Sino Wealth Electronic Ltd.");
        sparseArray.append(290, "AirTurn, Inc.");
        sparseArray.append(291, "Kinsa, Inc");
        sparseArray.append(292, "HID Global");
        sparseArray.append(293, "SEAT es");
        sparseArray.append(294, "Promethean Ltd.");
        sparseArray.append(295, "Salutica Allied Solutions");
        sparseArray.append(296, "GPSI Group Pty Ltd");
        sparseArray.append(297, "Nimble Devices Oy");
        sparseArray.append(298, "Changzhou Yongse Infotech Co.,Ltd.");
        sparseArray.append(299, "SportIQ");
        sparseArray.append(300, "TEMEC Instruments B.V.");
        sparseArray.append(301, "Sony Corporation");
        sparseArray.append(302, "ASSA ABLOY");
        sparseArray.append(303, "Clarion Co. Inc.");
        sparseArray.append(304, "Warehouse Innovations");
        sparseArray.append(305, "Cypress Semiconductor");
        sparseArray.append(306, "MADS Inc");
        sparseArray.append(307, "Blue Maestro Limited");
        sparseArray.append(308, "Resolution Products,Ltd.");
        sparseArray.append(309, "Aireware LLC");
        sparseArray.append(310, "Silvair, Inc.");
        sparseArray.append(311, "Prestigio Plaza Ltd.");
        sparseArray.append(312, "NTEO Inc.");
        sparseArray.append(313, "Focus Systems Corporation");
        sparseArray.append(314, "Tencent Holdings Ltd.");
        sparseArray.append(315, "Allegion");
        sparseArray.append(TypedValues.AttributesType.TYPE_PATH_ROTATE, "Murata Manufacturing Co.,Ltd.");
        sparseArray.append(TypedValues.AttributesType.TYPE_EASING, "WirelessWERX");
        sparseArray.append(TypedValues.AttributesType.TYPE_PIVOT_TARGET, "Nod, Inc.");
        sparseArray.append(319, "B&B Manufacturing Company");
        sparseArray.append(320, "Alpine Electronics (China,Co.,Ltd");
        sparseArray.append(321, "FedEx Services");
        sparseArray.append(322, "Grape Systems Inc.");
        sparseArray.append(323, "Bkon Connect");
        sparseArray.append(324, "Lintech GmbH");
        sparseArray.append(325, "Novatel Wireless");
        sparseArray.append(326, "Ciright");
        sparseArray.append(327, "Mighty Cast, Inc.");
        sparseArray.append(328, "Ambimat Electronics");
        sparseArray.append(329, "Perytons Ltd.");
        sparseArray.append(330, "Tivoli Audio,LLC");
        sparseArray.append(331, "Master Lock");
        sparseArray.append(332, "Mesh-Net Ltd");
        sparseArray.append(333, "HUIZHOU DESAY SV AUTOMOTIVE CO.,LTD.");
        sparseArray.append(334, "Tangerine, Inc.");
        sparseArray.append(335, "B&W Group Ltd.");
        sparseArray.append(336, "Pioneer Corporation");
        sparseArray.append(337, "OnBeep");
        sparseArray.append(338, "Vernier Software & Technology");
        sparseArray.append(339, "ROL Ergo");
        sparseArray.append(340, "Pebble Technology");
        sparseArray.append(FacebookRequestErrorClassification.EC_TOO_MANY_USER_ACTION_CALLS, "NETATMO");
        sparseArray.append(342, "Accumulate AB");
        sparseArray.append(343, "Anhui Huami Information Technology Co.,Ltd.");
        sparseArray.append(344, "Inmite s.r.o.");
        sparseArray.append(345, "ChefSteps, Inc.");
        sparseArray.append(346, "micas AG");
        sparseArray.append(347, "Biomedical Research Ltd.");
        sparseArray.append(348, "Pitius Tec S.L.");
        sparseArray.append(349, "Estimote, Inc.");
        sparseArray.append(350, "Unikey Technologies, Inc.");
        sparseArray.append(351, "Timer Cap Co.");
        sparseArray.append(352, "AwoX");
        sparseArray.append(353, "yikes");
        sparseArray.append(354, "MADSGlobalNZ Ltd.");
        sparseArray.append(355, "PCH International");
        sparseArray.append(356, "Qingdao Yeelink Information Technology Co.,Ltd.");
        sparseArray.append(357, "Milwaukee Tool (Formally Milwaukee Electric Tools);");
        sparseArray.append(358, "MISHIK Pte Ltd");
        sparseArray.append(359, "Ascensia Diabetes Care US Inc.");
        sparseArray.append(360, "Spicebox LLC");
        sparseArray.append(361, "emberlight");
        sparseArray.append(362, "Cooper-Atkins Corporation");
        sparseArray.append(363, "Qblinks");
        sparseArray.append(364, "MYSPHERA");
        sparseArray.append(365, "LifeScan Inc");
        sparseArray.append(366, "Volantic AB");
        sparseArray.append(367, "Podo Labs, Inc");
        sparseArray.append(368, "Roche Diabetes Care AG");
        sparseArray.append(369, "Amazon Fulfillment Service");
        sparseArray.append(370, "Connovate Technology Private Limited");
        sparseArray.append(371, "Kocomojo,LLC");
        sparseArray.append(372, "Everykey Inc.");
        sparseArray.append(373, "Dynamic Controls");
        sparseArray.append(374, "SentriLock");
        sparseArray.append(375, "I-SYST inc.");
        sparseArray.append(376, "CASIO COMPUTER CO.,LTD.");
        sparseArray.append(377, "LAPIS Semiconductor Co.,Ltd.");
        sparseArray.append(378, "Telemonitor, Inc.");
        sparseArray.append(379, "taskit GmbH");
        sparseArray.append(380, "Daimler AG");
        sparseArray.append(381, "BatAndCat");
        sparseArray.append(382, "BluDotz Ltd");
        sparseArray.append(383, "XTel Wireless ApS");
        sparseArray.append(RendererCapabilities.DECODER_SUPPORT_MASK, "Gigaset Communications GmbH");
        sparseArray.append(385, "Gecko Health Innovations, Inc.");
        sparseArray.append(386, "HOP Ubiquitous");
        sparseArray.append(387, "Walt Disney");
        sparseArray.append(388, "Nectar");
        sparseArray.append(389, "bel'apps LLC");
        sparseArray.append(390, "CORE Lighting Ltd");
        sparseArray.append(391, "Seraphim Sense Ltd");
        sparseArray.append(392, "Unico RBC");
        sparseArray.append(393, "Physical Enterprises Inc.");
        sparseArray.append(394, "Able Trend Technology Limited");
        sparseArray.append(395, "Konica Minolta, Inc.");
        sparseArray.append(396, "Wilo SE");
        sparseArray.append(397, "Extron Design Services");
        sparseArray.append(398, "Fitbit, Inc.");
        sparseArray.append(399, "Fireflies Systems");
        sparseArray.append(400, "Intelletto Technologies Inc.");
        sparseArray.append(401, "FDK CORPORATION");
        sparseArray.append(TypedValues.CycleType.TYPE_VISIBILITY, "Cloudleaf, Inc");
        sparseArray.append(403, "Maveric Automation LLC");
        sparseArray.append(Common.HTTP_STATUS_NOT_FOUND, "Acoustic Stream Corporation");
        sparseArray.append(DeviceCommonConstants.RESULT_CODE_ADDRESS_STATUS, "Zuli");
        sparseArray.append(406, "Paxton Access Ltd");
        sparseArray.append(407, "WiSilica Inc.");
        sparseArray.append(ErrorCode.ERROR_CODE_TIMEOUT, "VENGIT Korlatolt Felelossegu Tarsasag");
        sparseArray.append(Common.HTTP_STATUS_CONFLICT, "SALTO SYSTEMS S.L.");
        sparseArray.append(410, "TRON Forum (formerly T-Engine Forum);");
        sparseArray.append(411, "CUBETECH s.r.o.");
        sparseArray.append(FacebookRequestErrorClassification.EC_APP_NOT_INSTALLED, "Cokiya Incorporated");
        sparseArray.append(413, "CVS Health");
        sparseArray.append(414, "Ceruus");
        sparseArray.append(415, "Strainstall Ltd");
        sparseArray.append(416, "Channel Enterprises (HK,Ltd.");
        sparseArray.append(417, "FIAMM");
        sparseArray.append(418, "GIGALANE.CO.);LTD");
        sparseArray.append(AntiBrush.STATUS_BRUSH, "EROAD");
        sparseArray.append(420, "Mine Safety Appliances");
        sparseArray.append(421, "Icon Health and Fitness");
        sparseArray.append(422, "Asandoo GmbH");
        sparseArray.append(TypedValues.CycleType.TYPE_WAVE_PERIOD, "ENERGOUS CORPORATION");
        sparseArray.append(424, "Taobao");
        sparseArray.append(TypedValues.CycleType.TYPE_WAVE_PHASE, "Canon Inc.");
        sparseArray.append(426, "Geophysical Technology Inc.");
        sparseArray.append(427, "Facebook, Inc.");
        sparseArray.append(428, "Trividia Health, Inc.");
        sparseArray.append(Common.HTTP_STATUS_TOO_MANY_REQUESTS, "FlightSafety International");
        sparseArray.append(430, "Earlens Corporation");
        sparseArray.append(431, "Sunrise Micro Devices, Inc.");
        sparseArray.append(432, "Star Micronics Co.,Ltd.");
        sparseArray.append(433, "Netizens Sp. z o.o.");
        sparseArray.append(434, "Nymi Inc.");
        sparseArray.append(435, "Nytec, Inc.");
        sparseArray.append(436, "Trineo Sp. z o.o.");
        sparseArray.append(437, "Nest Labs Inc.");
        sparseArray.append(438, "LM Technologies Ltd");
        sparseArray.append(439, "General Electric Company");
        sparseArray.append(440, "i+D3 S.L.");
        sparseArray.append(441, "HANA Micron");
        sparseArray.append(442, "Stages Cycling LLC");
        sparseArray.append(Constants.PORT, "Cochlear Bone Anchored Solutions AB");
        sparseArray.append(444, "SenionLab AB");
        sparseArray.append(445, "Syszone Co.,Ltd");
        sparseArray.append(446, "Pulsate Mobile Ltd.");
        sparseArray.append(447, "Hong Kong HunterSun Electronic Limited");
        sparseArray.append(448, "pironex GmbH");
        sparseArray.append(449, "BRADATECH Corp.");
        sparseArray.append(450, "Transenergooil AG");
        sparseArray.append(451, "Bunch");
        sparseArray.append(452, "DME Microelectronics");
        sparseArray.append(453, "Bitcraze AB");
        sparseArray.append(454, "HASWARE Inc.");
        sparseArray.append(455, "Abiogenix Inc.");
        sparseArray.append(456, "Poly-Control ApS");
        sparseArray.append(457, "Avi-on");
        sparseArray.append(FacebookRequestErrorClassification.ESC_APP_NOT_INSTALLED, "Laerdal Medical AS");
        sparseArray.append(459, "Fetch My Pet");
        sparseArray.append(460, "Sam Labs Ltd.");
        sparseArray.append(461, "Chengdu Synwing Technology Ltd");
        sparseArray.append(462, "HOUWA SYSTEM DESIGN,k.k.");
        sparseArray.append(463, "BSH");
        sparseArray.append(464, "Primus Inter Pares Ltd");
        sparseArray.append(465, "August Home, Inc");
        sparseArray.append(466, "Gill Electronics");
        sparseArray.append(467, "Sky Wave Design");
        sparseArray.append(468, "Newlab S.r.l.");
        sparseArray.append(469, "ELAD srl");
        sparseArray.append(470, "G-wearables inc.");
        sparseArray.append(471, "Squadrone Systems Inc.");
        sparseArray.append(472, "Code Corporation");
        sparseArray.append(473, "Savant Systems LLC");
        sparseArray.append(474, "Logitech International SA");
        sparseArray.append(475, "Innblue Consulting");
        sparseArray.append(476, "iParking Ltd.");
        sparseArray.append(477, "Koninklijke Philips Electronics N.V.");
        sparseArray.append(478, "Minelab Electronics Pty Limited");
        sparseArray.append(479, "Bison Group Ltd.");
        sparseArray.append(480, "Widex A/S");
        sparseArray.append(481, "Jolla Ltd");
        sparseArray.append(482, "Lectronix, Inc.");
        sparseArray.append(483, "Caterpillar Inc");
        sparseArray.append(BuildConfig.VERSION_CODE, "Freedom Innovations");
        sparseArray.append(485, "Dynamic Devices Ltd");
        sparseArray.append(486, "Technology Solutions (UK,Ltd");
        sparseArray.append(487, "IPS Group Inc.");
        sparseArray.append(488, "STIR");
        sparseArray.append(489, "Sano, Inc.");
        sparseArray.append(490, "Advanced Application Design, Inc.");
        sparseArray.append(491, "AutoMap LLC");
        sparseArray.append(492, "Spreadtrum Communications Shanghai Ltd");
        sparseArray.append(FacebookRequestErrorClassification.ESC_APP_INACTIVE, "CuteCircuit LTD");
        sparseArray.append(494, "Valeo Service");
        sparseArray.append(495, "Fullpower Technologies, Inc.");
        sparseArray.append(496, "KloudNation");
        sparseArray.append(497, "Zebra Technologies Corporation");
        sparseArray.append(498, "Itron, Inc.");
        sparseArray.append(499, "The University of Tokyo");
        sparseArray.append(500, "UTC Fire and Security");
        sparseArray.append(501, "Cool Webthings Limited");
        sparseArray.append(502, "DJO Global");
        sparseArray.append(503, "Gelliner Limited");
        sparseArray.append(504, "Anyka (Guangzhou,Microelectronics Technology Co,LTD");
        sparseArray.append(505, "Medtronic Inc.");
        sparseArray.append(506, "Gozio Inc.");
        sparseArray.append(TypedValues.PositionType.TYPE_PERCENT_Y, "Form Lifting,LLC");
        sparseArray.append(TypedValues.PositionType.TYPE_CURVE_FIT, "Wahoo Fitness,LLC");
        sparseArray.append(509, "Kontakt Micro-Location Sp. z o.o.");
        sparseArray.append(TypedValues.PositionType.TYPE_POSITION_TYPE, "Radio Systems Corporation");
        sparseArray.append(FrameMetricsAggregator.EVERY_DURATION, "Freescale Semiconductor, Inc.");
        sparseArray.append(512, "Verifone Systems Pte Ltd. Taiwan Branch");
        sparseArray.append(513, "AR Timing");
        sparseArray.append(514, "Rigado LLC");
        sparseArray.append(DeviceCommonConstants.WHAT_ERROR_SEND_SUCCESS, "Kemppi Oy");
        sparseArray.append(DeviceCommonConstants.WHAT_ERROR_ZCONFIG_TIMEOUT, "Tapcentive Inc.");
        sparseArray.append(517, "Smartbotics Inc.");
        sparseArray.append(DeviceCommonConstants.WHAT_NETWORK_NOT_FOUND, "Otter Products,LLC");
        sparseArray.append(DeviceCommonConstants.WHAT_DHCP_START_FAILED, "STEMP Inc.");
        sparseArray.append(DeviceCommonConstants.WHAT_DHCP_TIMEOUT, "LumiGeek LLC");
        sparseArray.append(DeviceCommonConstants.WHAT_GW_CONN_TIMEOUT, "InvisionHeart Inc.");
        sparseArray.append(DeviceCommonConstants.WHAT_GW_AUTH_FAILED, "Macnica Inc.");
        sparseArray.append(DeviceCommonConstants.WHAT_DEVICE_CONNECT_SUCCESS, "Jaguar Land Rover Limited");
        sparseArray.append(524, "CoroWare Technologies, Inc");
        sparseArray.append(525, "Simplo Technology Co.,LTD");
        sparseArray.append(526, "Omron Healthcare Co.,LTD");
        sparseArray.append(527, "Comodule GMBH");
        sparseArray.append(528, "ikeGPS");
        sparseArray.append(529, "Telink Semiconductor Co. Ltd");
        sparseArray.append(530, "Interplan Co.,Ltd");
        sparseArray.append(531, "Wyler AG");
        sparseArray.append(532, "IK Multimedia Production srl");
        sparseArray.append(533, "Lukoton Experience Oy");
        sparseArray.append(534, "MTI Ltd");
        sparseArray.append(535, "Tech4home,Lda");
        sparseArray.append(536, "Hiotech AB");
        sparseArray.append(537, "DOTT Limited");
        sparseArray.append(538, "Blue Speck Labs,LLC");
        sparseArray.append(539, "Cisco Systems, Inc");
        sparseArray.append(540, "Mobicomm Inc");
        sparseArray.append(541, "Edamic");
        sparseArray.append(542, "Goodnet,Ltd");
        sparseArray.append(543, "Luster Leaf Products Inc");
        sparseArray.append(544, "Manus Machina BV");
        sparseArray.append(545, "Mobiquity Networks Inc");
        sparseArray.append(546, "Praxis Dynamics");
        sparseArray.append(547, "Philip Morris Products S.A.");
        sparseArray.append(548, "Comarch SA");
        sparseArray.append(549, "Nestl Nespresso S.A.");
        sparseArray.append(550, "Merlinia A/S");
        sparseArray.append(551, "LifeBEAM Technologies");
        sparseArray.append(552, "Twocanoes Labs,LLC");
        sparseArray.append(553, "Muoverti Limited");
        sparseArray.append(RtspMessageChannel.DEFAULT_RTSP_PORT, "Stamer Musikanlagen GMBH");
        sparseArray.append(555, "Tesla Motors");
        sparseArray.append(556, "Pharynks Corporation");
        sparseArray.append(557, "Lupine");
        sparseArray.append(558, "Siemens AG");
        sparseArray.append(559, "Huami (Shanghai,Culture Communication CO.,LTD");
        sparseArray.append(560, "Foster Electric Company,Ltd");
        sparseArray.append(UIMessageConstants.QR_CONFIRM_USER_NOT_LOGIN, "ETA SA");
        sparseArray.append(UIMessageConstants.QR_CONFIRM_DOMAIN_MISMATCH, "x-Senso Solutions Kft");
        sparseArray.append(563, "Shenzhen SuLong Communication Ltd");
        sparseArray.append(564, "FengFan (BeiJing,Technology Co,Ltd");
        sparseArray.append(565, "Qrio Inc");
        sparseArray.append(566, "Pitpatpet Ltd");
        sparseArray.append(567, "MSHeli s.r.l.");
        sparseArray.append(568, "Trakm8 Ltd");
        sparseArray.append(569, "JIN CO,Ltd");
        sparseArray.append(570, "Alatech Tehnology");
        sparseArray.append(571, "Beijing CarePulse Electronic Technology Co,Ltd");
        sparseArray.append(572, "Awarepoint");
        sparseArray.append(573, "ViCentra B.V.");
        sparseArray.append(574, "Raven Industries");
        sparseArray.append(575, "WaveWare Technologies Inc.");
        sparseArray.append(576, "Argenox Technologies");
        sparseArray.append(577, "Bragi GmbH");
        sparseArray.append(578, "16Lab Inc");
        sparseArray.append(579, "Masimo Corp");
        sparseArray.append(580, "Iotera Inc");
        sparseArray.append(581, "Endress+Hauser");
        sparseArray.append(582, "ACKme Networks, Inc.");
        sparseArray.append(583, "FiftyThree Inc.");
        sparseArray.append(584, "Parker Hannifin Corp");
        sparseArray.append(585, "Transcranial Ltd");
        sparseArray.append(586, "Uwatec AG");
        sparseArray.append(587, "Orlan LLC");
        sparseArray.append(588, "Blue Clover Devices");
        sparseArray.append(589, "M-Way Solutions GmbH");
        sparseArray.append(590, "Microtronics Engineering GmbH");
        sparseArray.append(591, "Schneider Schreibgerte GmbH");
        sparseArray.append(592, "Sapphire Circuits LLC");
        sparseArray.append(593, "Lumo Bodytech Inc.");
        sparseArray.append(594, "UKC Technosolution");
        sparseArray.append(595, "Xicato Inc.");
        sparseArray.append(596, "Playbrush");
        sparseArray.append(597, "Dai Nippon Printing Co.,Ltd.");
        sparseArray.append(598, "G24 Power Limited");
        sparseArray.append(599, "AdBabble Local Commerce Inc.");
        sparseArray.append(600, "Devialet SA");
        sparseArray.append(601, "ALTYOR");
        sparseArray.append(TypedValues.MotionType.TYPE_QUANTIZE_MOTION_PHASE, "University of Applied Sciences Valais/Haute Ecole Valaisanne");
        sparseArray.append(TypedValues.MotionType.TYPE_EASING, "Five Interactive,LLC dba Zendo");
        sparseArray.append(TypedValues.MotionType.TYPE_QUANTIZE_INTERPOLATOR, "NetEaseHangzhouNetwork co.Ltd.");
        sparseArray.append(TypedValues.MotionType.TYPE_ANIMATE_RELATIVE_TO, "Lexmark International Inc.");
        sparseArray.append(TypedValues.MotionType.TYPE_ANIMATE_CIRCLEANGLE_TO, "Fluke Corporation");
        sparseArray.append(TypedValues.MotionType.TYPE_PATHMOTION_ARC, "Yardarm Technologies");
        sparseArray.append(TypedValues.MotionType.TYPE_DRAW_PATH, "SensaRx");
        sparseArray.append(TypedValues.MotionType.TYPE_POLAR_RELATIVETO, "SECVRE GmbH");
        sparseArray.append(TypedValues.MotionType.TYPE_QUANTIZE_MOTIONSTEPS, "Glacial Ridge Technologies");
        sparseArray.append(TypedValues.MotionType.TYPE_QUANTIZE_INTERPOLATOR_TYPE, "Identiv, Inc.");
        sparseArray.append(TypedValues.MotionType.TYPE_QUANTIZE_INTERPOLATOR_ID, "DDS, Inc.");
        sparseArray.append(613, "SMK Corporation");
        sparseArray.append(614, "Schawbel Technologies LLC");
        sparseArray.append(615, "XMI Systems SA");
        sparseArray.append(616, "Cerevo");
        sparseArray.append(617, "Torrox GmbH & Co KG");
        sparseArray.append(618, "Gemalto");
        sparseArray.append(619, "DEKA Research & Development Corp.");
        sparseArray.append(620, "Domster Tadeusz Szydlowski");
        sparseArray.append(621, "Technogym SPA");
        sparseArray.append(622, "FLEURBAEY BVBA");
        sparseArray.append(623, "Aptcode Solutions");
        sparseArray.append(624, "LSI ADL Technology");
        sparseArray.append(625, "Animas Corp");
        sparseArray.append(626, "Alps Electric Co.,Ltd.");
        sparseArray.append(627, "OCEASOFT");
        sparseArray.append(628, "Motsai Research");
        sparseArray.append(629, "Geotab");
        sparseArray.append(AIWatchListener.AI_WATCH_STATUS_NOTIFY, "E.G.O. Elektro-Gertebau GmbH");
        sparseArray.append(AIWatchListener.AI_WATCH_VOICE_DATA_NOTIFY, "bewhere inc");
        sparseArray.append(632, "Johnson Outdoors Inc");
        sparseArray.append(633, "steute Schaltgerate GmbH & Co. KG");
        sparseArray.append(634, "Ekomini inc.");
        sparseArray.append(635, "DEFA AS");
        sparseArray.append(636, "Aseptika Ltd");
        sparseArray.append(637, "HUAWEI Technologies Co.,Ltd. ( );");
        sparseArray.append(638, "HabitAware,LLC");
        sparseArray.append(639, "ruwido austria gmbh");
        sparseArray.append(640, "ITEC corporation");
        sparseArray.append(641, "StoneL");
        sparseArray.append(642, "Sonova AG");
        sparseArray.append(643, "Maven Machines, Inc.");
        sparseArray.append(644, "Synapse Electronics");
        sparseArray.append(645, "Standard Innovation Inc.");
        sparseArray.append(646, "RF Code, Inc.");
        sparseArray.append(647, "Wally Ventures S.L.");
        sparseArray.append(648, "Willowbank Electronics Ltd");
        sparseArray.append(649, "SK Telecom");
        sparseArray.append(650, "Jetro AS");
        sparseArray.append(651, "Code Gears LTD");
        sparseArray.append(652, "NANOLINK APS");
        sparseArray.append(653, "IF,LLC");
        sparseArray.append(654, "RF Digital Corp");
        sparseArray.append(655, "Church & Dwight Co., Inc");
        sparseArray.append(656, "Multibit Oy");
        sparseArray.append(657, "CliniCloud Inc");
        sparseArray.append(658, "SwiftSensors");
        sparseArray.append(659, "Blue Bite");
        sparseArray.append(660, "ELIAS GmbH");
        sparseArray.append(661, "Sivantos GmbH");
        sparseArray.append(662, "Petzl");
        sparseArray.append(663, "storm power ltd");
        sparseArray.append(664, "EISST Ltd");
        sparseArray.append(665, "Inexess Technology Simma KG");
        sparseArray.append(666, "Currant, Inc.");
        sparseArray.append(667, "C2 Development, Inc.");
        sparseArray.append(668, "Blue Sky Scientific,LLC");
        sparseArray.append(669, "ALOTTAZS LABS,LLC");
        sparseArray.append(670, "Kupson spol. s r.o.");
        sparseArray.append(671, "Areus Engineering GmbH");
        sparseArray.append(672, "Impossible Camera GmbH");
        sparseArray.append(673, "InventureTrack Systems");
        sparseArray.append(674, "LockedUp");
        sparseArray.append(675, "Itude");
        sparseArray.append(676, "Pacific Lock Company");
        sparseArray.append(677, "Tendyron Corporation ( );");
        sparseArray.append(678, "Robert Bosch GmbH");
        sparseArray.append(679, "Illuxtron international B.V.");
        sparseArray.append(680, "miSport Ltd.");
        sparseArray.append(681, "Chargelib");
        sparseArray.append(682, "Doppler Lab");
        sparseArray.append(683, "BBPOS Limited");
        sparseArray.append(684, "RTB Elektronik GmbH & Co. KG");
        sparseArray.append(685, "Rx Networks, Inc.");
        sparseArray.append(686, "WeatherFlow, Inc.");
        sparseArray.append(687, "Technicolor USA Inc.");
        sparseArray.append(688, "Bestechnic(Shanghai););Ltd");
        sparseArray.append(689, "Raden Inc");
        sparseArray.append(690, "JouZen Oy");
        sparseArray.append(691, "CLABER S.P.A.");
        sparseArray.append(692, "Hyginex, Inc.");
        sparseArray.append(693, "HANSHIN ELECTRIC RAILWAY CO.);LTD.");
        sparseArray.append(694, "Schneider Electric");
        sparseArray.append(695, "Oort Technologies LLC");
        sparseArray.append(Crop.REQUEST_EDIT_CROP, "Chrono Therapeutics");
        sparseArray.append(697, "Rinnai Corporation");
        sparseArray.append(698, "Swissprime Technologies AG");
        sparseArray.append(699, "Koha.);Co.Ltd");
        sparseArray.append(TypedValues.TransitionType.TYPE_DURATION, "Genevac Ltd");
        sparseArray.append(TypedValues.TransitionType.TYPE_FROM, "Chemtronics");
        sparseArray.append(TypedValues.TransitionType.TYPE_TO, "Seguro Technology Sp. z o.o.");
        sparseArray.append(703, "Redbird Flight Simulations");
        sparseArray.append(TypedValues.TransitionType.TYPE_AUTO_TRANSITION, "Dash Robotics");
        sparseArray.append(TypedValues.TransitionType.TYPE_INTERPOLATOR, "LINE Corporation");
        sparseArray.append(TypedValues.TransitionType.TYPE_STAGGERED, "Guillemot Corporation");
        sparseArray.append(TypedValues.TransitionType.TYPE_TRANSITION_FLAGS, "Techtronic Power Tools Technology Limited");
        sparseArray.append(708, "Wilson Sporting Goods");
        sparseArray.append(709, "Lenovo (Singapore,Pte Ltd. ( );");
        sparseArray.append(710, "Ayatan Sensors");
        sparseArray.append(711, "Electronics Tomorrow Limited");
        sparseArray.append(712, "VASCO Data Security International, Inc.");
        sparseArray.append(713, "PayRange Inc.");
        sparseArray.append(714, "ABOV Semiconductor");
        sparseArray.append(715, "AINA-Wireless Inc.");
        sparseArray.append(716, "Eijkelkamp Soil & Water");
        sparseArray.append(717, "BMA ergonomics b.v.");
        sparseArray.append(718, "Teva Branded Pharmaceutical Products R&D, Inc.");
        sparseArray.append(AdaptiveTrackSelection.DEFAULT_MAX_HEIGHT_TO_DISCARD, "Anima");
        sparseArray.append(720, "3M");
        sparseArray.append(721, "Empatica Srl");
        sparseArray.append(722, "Afero, Inc.");
        sparseArray.append(723, "Powercast Corporation");
        sparseArray.append(724, "Secuyou ApS");
        sparseArray.append(725, "OMRON Corporation");
        sparseArray.append(726, "Send Solutions");
        sparseArray.append(727, "NIPPON SYSTEMWARE CO.);LTD.");
        sparseArray.append(728, "Neosfar");
        sparseArray.append(729, "Fliegl Agrartechnik GmbH");
        sparseArray.append(730, "Gilvader");
        sparseArray.append(731, "Digi International Inc (R);");
        sparseArray.append(732, "DeWalch Technologies, Inc.");
        sparseArray.append(733, "Flint Rehabilitation Devices,LLC");
        sparseArray.append(734, "Samsung SDS Co.,Ltd.");
        sparseArray.append(735, "Blur Product Development");
        sparseArray.append(736, "University of Michigan");
        sparseArray.append(737, "Victron Energy BV");
        sparseArray.append(738, "NTT docomo");
        sparseArray.append(739, "Carmanah Technologies Corp.");
        sparseArray.append(740, "Bytestorm Ltd.");
        sparseArray.append(741, "Espressif Incorporated ( (,);");
        sparseArray.append(742, "Unwire");
        sparseArray.append(743, "Connected Yard, Inc.");
        sparseArray.append(744, "American Music Environments");
        sparseArray.append(745, "Sensogram Technologies, Inc.");
        sparseArray.append(746, "Fujitsu Limited");
        sparseArray.append(747, "Ardic Technology");
        sparseArray.append(748, "Delta Systems, Inc");
        sparseArray.append(749, "HTC Corporation");
        sparseArray.append(750, "Citizen Holdings Co.,Ltd.");
        sparseArray.append(751, "SMART-INNOVATION.inc");
        sparseArray.append(752, "Blackrat Software");
        sparseArray.append(753, "The Idea Cave,LLC");
        sparseArray.append(754, "GoPro, Inc.");
        sparseArray.append(755, "AuthAir, Inc");
        sparseArray.append(756, "Vensi, Inc.");
        sparseArray.append(757, "Indagem Tech LLC");
        sparseArray.append(758, "Intemo Technologies");
        sparseArray.append(759, "DreamVisions co.,Ltd.");
        sparseArray.append(760, "Runteq Oy Ltd");
        sparseArray.append(761, "IMAGINATION TECHNOLOGIES LTD");
        sparseArray.append(762, "CoSTAR TEchnologies");
        sparseArray.append(763, "Clarius Mobile Health Corp.");
        sparseArray.append(764, "Shanghai Frequen Microelectronics Co.,Ltd.");
        sparseArray.append(765, "Uwanna, Inc.");
        sparseArray.append(766, "Lierda Science & Technology Group Co.,Ltd.");
        sparseArray.append(767, "Silicon Laboratories");
        sparseArray.append(768, "World Moto Inc.");
        sparseArray.append(769, "Giatec Scientific Inc.");
        sparseArray.append(770, "Loop Devices, Inc");
        sparseArray.append(771, "IACA electronique");
        sparseArray.append(772, "Proxy Technologies, Inc.");
        sparseArray.append(773, "Swipp ApS");
        sparseArray.append(774, "Life Laboratory Inc.");
        sparseArray.append(775, "FUJI INDUSTRIAL CO.);LTD.");
        sparseArray.append(776, "Surefire,LLC");
        sparseArray.append(777, "Dolby Labs");
        sparseArray.append(778, "Ellisys");
        sparseArray.append(779, "Magnitude Lighting Converters");
        sparseArray.append(780, "Hilti AG");
        sparseArray.append(781, "Devdata S.r.l.");
        sparseArray.append(782, "Deviceworx");
        sparseArray.append(783, "Shortcut Labs");
        sparseArray.append(784, "SGL Italia S.r.l.");
        sparseArray.append(785, "PEEQ DATA");
        sparseArray.append(786, "Ducere Technologies Pvt Ltd");
        sparseArray.append(787, "DiveNav, Inc.");
        sparseArray.append(788, "RIIG AI Sp. z o.o.");
        sparseArray.append(789, "Thermo Fisher Scientific");
        sparseArray.append(790, "AG Measurematics Pvt. Ltd.");
        sparseArray.append(791, "CHUO Electronics CO.,LTD.");
        sparseArray.append(792, "Aspenta International");
        sparseArray.append(793, "Eugster Frismag AG");
        sparseArray.append(794, "Amber wireless GmbH");
        sparseArray.append(795, "HQ Inc");
        sparseArray.append(796, "Lab Sensor Solutions");
        sparseArray.append(797, "Enterlab ApS");
        sparseArray.append(798, "Eyefi, Inc.");
        sparseArray.append(799, "MetaSystem S.p.A.");
        sparseArray.append(800, "SONO ELECTRONICS. CO.,LTD");
        sparseArray.append(801, "Jewelbots");
        sparseArray.append(802, "Compumedics Limited");
        sparseArray.append(803, "Rotor Bike Components");
        sparseArray.append(804, "Astro, Inc.");
        sparseArray.append(805, "Amotus Solutions");
        sparseArray.append(806, "Healthwear Technologies (Changzhou);Ltd");
        sparseArray.append(807, "Essex Electronics");
        sparseArray.append(808, "Grundfos A/S");
        sparseArray.append(809, "Eargo, Inc.");
        sparseArray.append(810, "Electronic Design Lab");
        sparseArray.append(811, "ESYLUX");
        sparseArray.append(812, "NIPPON SMT.CO.);Ltd");
        sparseArray.append(813, "BM innovations GmbH");
        sparseArray.append(814, "indoormap");
        sparseArray.append(815, "OttoQ Inc");
        sparseArray.append(816, "North Pole Engineering");
        sparseArray.append(817, "3flares Technologies Inc.");
        sparseArray.append(818, "Electrocompaniet A.S.");
        sparseArray.append(819, "Mul-T-Lock");
        sparseArray.append(820, "Corentium AS");
        sparseArray.append(821, "Enlighted Inc");
        sparseArray.append(822, "GISTIC");
        sparseArray.append(823, "AJP2 Holdings,LLC");
        sparseArray.append(824, "COBI GmbH");
        sparseArray.append(825, "Blue Sky Scientific,LLC");
        sparseArray.append(826, "Appception, Inc.");
        sparseArray.append(827, "Courtney Thorne Limited");
        sparseArray.append(828, "Virtuosys");
        sparseArray.append(829, "TPV Technology Limited");
        sparseArray.append(830, "Monitra SA");
        sparseArray.append(831, "Automation Components, Inc.");
        sparseArray.append(832, "Letsense s.r.l.");
        sparseArray.append(833, "Etesian Technologies LLC");
        sparseArray.append(834, "GERTEC BRASIL LTDA.");
        sparseArray.append(835, "Drekker Development Pty. Ltd.");
        sparseArray.append(836, "Whirl Inc");
        sparseArray.append(837, "Locus Positioning");
        sparseArray.append(838, "Acuity Brands Lighting, Inc");
        sparseArray.append(839, "Prevent Biometrics");
        sparseArray.append(840, "Arioneo");
        sparseArray.append(841, "VersaMe");
        sparseArray.append(842, "Vaddio");
        sparseArray.append(843, "Libratone A/S");
        sparseArray.append(844, "HM Electronics, Inc.");
        sparseArray.append(845, "TASER International, Inc.");
        sparseArray.append(846, "SafeTrust Inc.");
        sparseArray.append(847, "Heartland Payment Systems");
        sparseArray.append(848, "Bitstrata Systems Inc.");
        sparseArray.append(849, "Pieps GmbH");
        sparseArray.append(850, "iRiding(Xiamen);Technology Co.);Ltd.");
        sparseArray.append(851, "Alpha Audiotronics, Inc.");
        sparseArray.append(852, "TOPPAN FORMS CO.);LTD.");
        sparseArray.append(853, "Sigma Designs, Inc.");
        sparseArray.append(854, "Spectrum Brands, Inc.");
        sparseArray.append(855, "Polymap Wireless");
        sparseArray.append(856, "MagniWare Ltd.");
        sparseArray.append(857, "Novotec Medical GmbH");
        sparseArray.append(858, "Medicom Innovation Partner a/s");
        sparseArray.append(859, "Matrix Inc.");
        sparseArray.append(860, "Eaton Corporation");
        sparseArray.append(861, "KYS");
        sparseArray.append(862, "Naya Health, Inc.");
        sparseArray.append(863, "Acromag");
        sparseArray.append(864, "Insulet Corporation");
        sparseArray.append(865, "Wellinks Inc.");
        sparseArray.append(866, "ON Semiconductor");
        sparseArray.append(867, "FREELAP SA");
        sparseArray.append(868, "Favero Electronics Srl");
        sparseArray.append(869, "BioMech Sensor LLC");
        sparseArray.append(870, "BOLTT Sports technologies Private limited");
        sparseArray.append(871, "Saphe International");
        sparseArray.append(872, "Metormote AB");
        sparseArray.append(873, "littleBits");
        sparseArray.append(874, "SetPoint Medical");
        sparseArray.append(875, "BRControls Products BV");
        sparseArray.append(876, "Zipcar");
        sparseArray.append(877, "AirBolt Pty Ltd");
        sparseArray.append(878, "KeepTruckin Inc");
        sparseArray.append(879, "Motiv, Inc.");
        sparseArray.append(880, "Wazombi Labs O");
        sparseArray.append(881, "ORBCOMM");
        sparseArray.append(882, "Nixie Labs, Inc.");
        sparseArray.append(883, "AppNearMe Ltd");
        sparseArray.append(884, "Holman Industries");
        sparseArray.append(885, "Expain AS");
        sparseArray.append(886, "Electronic Temperature Instruments Ltd");
        sparseArray.append(887, "Plejd AB");
        sparseArray.append(888, "Propeller Health");
        sparseArray.append(889, "Shenzhen iMCO Electronic Technology Co.);Ltd");
        sparseArray.append(890, "Algoria");
        sparseArray.append(891, "Apption Labs Inc.");
        sparseArray.append(892, "Cronologics Corporation");
        sparseArray.append(893, "MICRODIA Ltd.");
        sparseArray.append(894, "lulabytes S.L.");
        sparseArray.append(895, "Nestec S.A.");
        sparseArray.append(896, "LLC \"MEGA-F service\"");
        sparseArray.append(897, "Sharp Corporation");
        sparseArray.append(898, "Precision Outcomes Ltd");
        sparseArray.append(899, "Kronos Incorporated");
        sparseArray.append(TypedValues.Custom.TYPE_INT, "OCOSMOS Co.,Ltd.");
        sparseArray.append(TypedValues.Custom.TYPE_FLOAT, "Embedded Electronic Solutions Ltd. dba e2Solutions");
        sparseArray.append(TypedValues.Custom.TYPE_COLOR, "Aterica Inc.");
        sparseArray.append(TypedValues.Custom.TYPE_STRING, "BluStor PMC, Inc.");
        sparseArray.append(TypedValues.Custom.TYPE_BOOLEAN, "Kapsch TrafficCom AB");
        sparseArray.append(TypedValues.Custom.TYPE_DIMENSION, "ActiveBlu Corporation");
        sparseArray.append(TypedValues.Custom.TYPE_REFERENCE, "Kohler Mira Limited");
        sparseArray.append(907, "Noke");
        sparseArray.append(908, "Appion Inc.");
        sparseArray.append(PictureConfig.REQUEST_CAMERA, "Resmed Ltd");
        sparseArray.append(910, "Crownstone B.V.");
        sparseArray.append(911, "Xiaomi Inc.");
        sparseArray.append(912, "INFOTECH s.r.o.");
        sparseArray.append(913, "Thingsquare AB");
        sparseArray.append(914, "T&D");
        sparseArray.append(915, "LAVAZZA S.p.A.");
        sparseArray.append(916, "Netclearance Systems, Inc.");
        sparseArray.append(917, "SDATAWAY");
        sparseArray.append(918, "BLOKS GmbH");
        sparseArray.append(919, "LEGO System A/S");
        sparseArray.append(920, "Thetatronics Ltd");
        sparseArray.append(921, "Nikon Corporation");
        sparseArray.append(922, "NeST");
        sparseArray.append(923, "South Silicon Valley Microelectronics");
        sparseArray.append(924, "ALE International");
        sparseArray.append(925, "CareView Communications, Inc.");
        sparseArray.append(926, "SchoolBoard Limited");
        sparseArray.append(927, "Molex Corporation");
        sparseArray.append(PDF417Common.MAX_CODEWORDS_IN_BARCODE, "IVT Wireless Limited");
        sparseArray.append(PDF417Common.NUMBER_OF_CODEWORDS, "Alpine Labs LLC");
        sparseArray.append(930, "Candura Instruments");
        sparseArray.append(931, "SmartMovt Technology Co.,Ltd");
        sparseArray.append(932, "Token Zero Ltd");
        sparseArray.append(933, "ACE CAD Enterprise Co.,Ltd. (ACECAD);");
        sparseArray.append(934, "Medela, Inc");
        sparseArray.append(935, "AeroScout");
        sparseArray.append(936, "Esrille Inc.");
        sparseArray.append(937, "THINKERLY SRL");
        sparseArray.append(938, "Exon Sp. z o.o.");
        sparseArray.append(939, "Meizu Technology Co.,Ltd.");
        sparseArray.append(940, "Smablo LTD");
        sparseArray.append(941, "XiQ");
        sparseArray.append(942, "Allswell Inc.");
        sparseArray.append(943, "Comm-N-Sense Corp DBA Verigo");
        sparseArray.append(944, "VIBRADORM GmbH");
        sparseArray.append(945, "Otodata Wireless Network Inc.");
        sparseArray.append(946, "Propagation Systems Limited");
        sparseArray.append(947, "Midwest Instruments & Controls");
        sparseArray.append(948, "Alpha Nodus, Inc.");
        sparseArray.append(949, "petPOMM, Inc");
        sparseArray.append(950, "Mattel");
        sparseArray.append(MessageConstants.JS_BRIDGE_METHOD_NOT_FOUND, "Airbly Inc.");
        sparseArray.append(MessageConstants.JS_BRIDGE_ANNOTATION_NOT_PRESENT, "A-Safe Limited");
        sparseArray.append(953, "FREDERIQUE CONSTANT SA");
        sparseArray.append(954, "Maxscend Microelectronics Company Limited");
        sparseArray.append(955, "Abbott Diabetes Care");
        sparseArray.append(956, "ASB Bank Ltd");
        sparseArray.append(957, "amadas");
        sparseArray.append(958, "Applied Science, Inc.");
        sparseArray.append(959, "iLumi Solutions Inc.");
        sparseArray.append(960, "Arch Systems Inc.");
        sparseArray.append(961, "Ember Technologies, Inc.");
        sparseArray.append(962, "Snapchat Inc");
        sparseArray.append(963, "Casambi Technologies Oy");
        sparseArray.append(964, "Pico Technology Inc.");
        sparseArray.append(965, "St. Jude Medical, Inc.");
        sparseArray.append(966, "Intricon");
        sparseArray.append(967, "Structural Health Systems, Inc.");
        sparseArray.append(968, "Avvel International");
        sparseArray.append(969, "Gallagher Group");
        sparseArray.append(970, "In2things Automation Pvt. Ltd.");
        sparseArray.append(971, "SYSDEV Srl");
        sparseArray.append(972, "Vonkil Technologies Ltd");
        sparseArray.append(973, "Wynd Technologies, Inc.");
        sparseArray.append(974, "CONTRINEX S.A.");
        sparseArray.append(975, "MIRA, Inc.");
        sparseArray.append(976, "Watteam Ltd");
        sparseArray.append(977, "Density Inc.");
        sparseArray.append(978, "IOT Pot India Private Limited");
        sparseArray.append(979, "Sigma Connectivity AB");
        sparseArray.append(980, "PEG PEREGO SPA");
        sparseArray.append(981, "Wyzelink Systems Inc.");
        sparseArray.append(982, "Yota Devices LTD");
        sparseArray.append(983, "FINSECUR");
        sparseArray.append(984, "Zen-Me Labs Ltd");
        sparseArray.append(985, "3IWare Co.,Ltd.");
        sparseArray.append(986, "EnOcean GmbH");
        sparseArray.append(987, "Instabeat, Inc");
        sparseArray.append(988, "Nima Labs");
        sparseArray.append(989, "Andreas Stihl AG & Co. KG");
        sparseArray.append(990, "Nathan Rhoades LLC");
        sparseArray.append(991, "Grob Technologies,LLC");
        sparseArray.append(992, "Actions (Zhuhai,Technology Co.,Limited");
        sparseArray.append(993, "SPD Development Company Ltd");
        sparseArray.append(994, "Sensoan Oy");
        sparseArray.append(995, "Qualcomm Life Inc");
        sparseArray.append(996, "Chip-ing AG");
        sparseArray.append(997, "ffly4u");
        sparseArray.append(998, "IoT Instruments Oy");
        sparseArray.append(999, "TRUE Fitness Technology");
        sparseArray.append(1000, "Reiner Kartengeraete GmbH & Co. KG.");
        sparseArray.append(1001, "SHENZHEN LEMONJOY TECHNOLOGY CO.,LTD.");
        sparseArray.append(1002, "Hello Inc.");
        sparseArray.append(1003, "Evollve Inc.");
        sparseArray.append(1004, "Jigowatts Inc.");
        sparseArray.append(1005, "BASIC MICRO.COM);INC.");
        sparseArray.append(1006, "CUBE TECHNOLOGIES");
        sparseArray.append(1007, "foolography GmbH");
        sparseArray.append(1008, "CLINK");
        sparseArray.append(1009, "Hestan Smart Cooking Inc.");
        sparseArray.append(1010, "WindowMaster A/S");
        sparseArray.append(1011, "Flowscape AB");
        sparseArray.append(1012, "PAL Technologies Ltd");
        sparseArray.append(1013, "WHERE, Inc.");
        sparseArray.append(1014, "Iton Technology Corp.");
        sparseArray.append(1015, "Owl Labs Inc.");
        sparseArray.append(1016, "Rockford Corp.");
        sparseArray.append(1017, "Becon Technologies Co.);Ltd.");
        sparseArray.append(1018, "Vyassoft Technologies Inc");
        sparseArray.append(1019, "Nox Medical");
        sparseArray.append(1020, "Kimberly-Clark");
        sparseArray.append(1021, "Trimble Navigation Ltd.");
        sparseArray.append(AnalyticsListener.EVENT_DRM_SESSION_ACQUIRED, "Littelfuse");
        sparseArray.append(1023, "Withings");
        sparseArray.append(1024, "i-developer IT Beratung UG");
        sparseArray.append(1025, "");
        sparseArray.append(AnalyticsListener.EVENT_DRM_KEYS_REMOVED, "Sears Holdings Corporation");
        sparseArray.append(AnalyticsListener.EVENT_DRM_SESSION_RELEASED, "Gantner Electronic GmbH");
        sparseArray.append(AnalyticsListener.EVENT_PLAYER_RELEASED, "Authomate Inc");
        sparseArray.append(AnalyticsListener.EVENT_AUDIO_CODEC_ERROR, "Vertex International, Inc.");
        sparseArray.append(AnalyticsListener.EVENT_VIDEO_CODEC_ERROR, "Airtago");
        sparseArray.append(AnalyticsListener.EVENT_AUDIO_TRACK_INITIALIZED, "Swiss Audio SA");
        sparseArray.append(AnalyticsListener.EVENT_AUDIO_TRACK_RELEASED, "ToGetHome Inc.");
        sparseArray.append(1033, "AXIS");
        sparseArray.append(1034, "Openmatics");
        sparseArray.append(1035, "Jana Care Inc.");
        sparseArray.append(1036, "Senix Corporation");
        sparseArray.append(1037, "NorthStar Battery Company,LLC");
        sparseArray.append(1038, "SKF (U.K.,Limited");
        sparseArray.append(1039, "CO-AX Technology, Inc.");
        sparseArray.append(1040, "Fender Musical Instruments");
        sparseArray.append(1041, "Luidia Inc");
        sparseArray.append(1042, "SEFAM");
        sparseArray.append(1043, "Wireless Cables Inc");
        sparseArray.append(1044, "Lightning Protection International Pty Ltd");
        sparseArray.append(1045, "Uber Technologies Inc");
        sparseArray.append(1046, "SODA GmbH");
        sparseArray.append(1047, "Fatigue Science");
        sparseArray.append(1048, "Alpine Electronics Inc.");
        sparseArray.append(1049, "Novalogy LTD");
        sparseArray.append(1050, "Friday Labs Limited");
        sparseArray.append(1051, "OrthoAccel Technologies");
        sparseArray.append(1052, "WaterGuru, Inc.");
        sparseArray.append(1053, "Benning Elektrotechnik und Elektronik GmbH & Co. KG");
        sparseArray.append(1054, "Dell Computer Corporation");
        sparseArray.append(1055, "Kopin Corporation");
        sparseArray.append(1056, "TecBakery GmbH");
        sparseArray.append(1057, "Backbone Labs, Inc.");
        sparseArray.append(1058, "DELSEY SA");
        sparseArray.append(1059, "Chargifi Limited");
        sparseArray.append(1060, "Trainesense Ltd.");
        sparseArray.append(1061, "Unify Software and Solutions GmbH & Co. KG");
        sparseArray.append(1062, "Husqvarna AB");
        sparseArray.append(1063, "Focus fleet and fuel management inc");
        sparseArray.append(1064, "SmallLoop,LLC");
        sparseArray.append(1065, "Prolon Inc.");
        sparseArray.append(1066, "BD Medical");
        sparseArray.append(1067, "iMicroMed Incorporated");
        sparseArray.append(1068, "Ticto N.V.");
        sparseArray.append(1069, "Meshtech AS");
        sparseArray.append(1070, "MemCachier Inc.");
        sparseArray.append(1071, "Danfoss A/S");
        sparseArray.append(1072, "SnapStyk Inc.");
        sparseArray.append(1073, "Amway Corporation");
        sparseArray.append(1074, "Silk Labs, Inc.");
        sparseArray.append(1075, "Pillsy Inc.");
        sparseArray.append(1076, "Hatch Baby, Inc.");
        sparseArray.append(1077, "Blocks Wearables Ltd.");
        sparseArray.append(1078, "Drayson Technologies (Europe,Limited");
        sparseArray.append(1079, "eBest IOT Inc.");
        sparseArray.append(1080, "Helvar Ltd");
        sparseArray.append(1081, "Radiance Technologies");
        sparseArray.append(1082, "Nuheara Limited");
        sparseArray.append(1083, "Appside co.,ltd.");
        sparseArray.append(1084, "DeLaval");
        sparseArray.append(1085, "Coiler Corporation");
        sparseArray.append(1086, "Thermomedics, Inc.");
        sparseArray.append(1087, "Tentacle Sync GmbH");
        sparseArray.append(1088, "Valencell, Inc.");
        sparseArray.append(1089, "iProtoXi Oy");
        sparseArray.append(1090, "SECOM CO.,LTD.");
        sparseArray.append(1091, "Tucker International LLC");
        sparseArray.append(1092, "Metanate Limited");
        sparseArray.append(1093, "Kobian Canada Inc.");
        sparseArray.append(1094, "NETGEAR, Inc.");
        sparseArray.append(1095, "Fabtronics Australia Pty Ltd");
        sparseArray.append(1096, "Grand Centrix GmbH");
        sparseArray.append(1097, "1UP USA.com llc");
        sparseArray.append(1098, "SHIMANO INC.");
        sparseArray.append(1099, "Nain Inc.");
        sparseArray.append(1100, "LifeStyle Lock,LLC");
        sparseArray.append(1101, "VEGA Grieshaber KG");
        sparseArray.append(PictureConfig.REQUEST_GO_SETTING, "Xtrava Inc.");
        sparseArray.append(1103, "TTS Tooltechnic Systems AG & Co. KG");
        sparseArray.append(1104, "Teenage Engineering AB");
        sparseArray.append(1105, "Tunstall Nordic AB");
        sparseArray.append(1106, "Svep Design Center AB");
        sparseArray.append(1107, "GreenPeak Technologies BV");
        sparseArray.append(1108, "Sphinx Electronics GmbH & Co KG");
        sparseArray.append(1109, "Atomation");
        sparseArray.append(1110, "Nemik Consulting Inc");
        sparseArray.append(1111, "RF INNOVATION");
        sparseArray.append(1112, "Mini Solution Co.,Ltd.");
        sparseArray.append(1113, "Lumenetix, Inc");
        sparseArray.append(1114, "2048450 Ontario Inc");
        sparseArray.append(1115, "SPACEEK LTD");
        sparseArray.append(1116, "Delta T Corporation");
        sparseArray.append(1117, "Boston Scientific Corporation");
        sparseArray.append(1118, "Nuviz, Inc.");
        sparseArray.append(1119, "Real Time Automation, Inc.");
        sparseArray.append(1120, "Kolibree");
        sparseArray.append(1121, "vhf elektronik GmbH");
        sparseArray.append(1122, "Bonsai Systems GmbH");
        sparseArray.append(1123, "Fathom Systems Inc.");
        sparseArray.append(1124, "Bellman & Symfon");
        sparseArray.append(1125, "International Forte Group LLC");
        sparseArray.append(1126, "CycleLabs Solutions inc.");
        sparseArray.append(1127, "Codenex Oy");
        sparseArray.append(1128, "Kynesim Ltd");
        sparseArray.append(1129, "Palago AB");
        sparseArray.append(1130, "INSIGMA INC.");
        sparseArray.append(1131, "PMD Solutions");
        sparseArray.append(1132, "Qingdao Realtime Technology Co.,Ltd.");
        sparseArray.append(1133, "BEGA Gantenbrink-Leuchten KG");
        sparseArray.append(1134, "Pambor Ltd.");
        sparseArray.append(1135, "Develco Products A/S");
        sparseArray.append(1136, "iDesign s.r.l.");
        sparseArray.append(1137, "TiVo Corp");
        sparseArray.append(1138, "Control-J Pty Ltd");
        sparseArray.append(1139, "Steelcase, Inc.");
        sparseArray.append(1140, "iApartment co.,ltd.");
        sparseArray.append(1141, "Icom inc.");
        sparseArray.append(1142, "Oxstren Wearable Technologies Private Limited");
        sparseArray.append(1143, "Blue Spark Technologies");
        sparseArray.append(1144, "FarSite Communications Limited");
        sparseArray.append(1145, "mywerk system GmbH");
        sparseArray.append(1146, "Sinosun Technology Co.,Ltd.");
        sparseArray.append(1147, "MIYOSHI ELECTRONICS CORPORATION");
        sparseArray.append(1148, "POWERMAT LTD");
        sparseArray.append(1149, "Occly LLC");
        sparseArray.append(1150, "OurHub Dev IvS");
        sparseArray.append(1151, "Pro-Mark, Inc.");
        sparseArray.append(1152, "Dynometrics Inc.");
        sparseArray.append(1153, "Quintrax Limited");
        sparseArray.append(1154, "POS Tuning Udo Vosshenrich GmbH & Co. KG");
        sparseArray.append(1155, "Multi Care Systems B.V.");
        sparseArray.append(1156, "Revol Technologies Inc");
        sparseArray.append(1157, "SKIDATA AG");
        sparseArray.append(1158, "DEV TECNOLOGIA INDUSTRIA,COMERCIO E MANUTENCAO DE EQUIPAMENTOS LTDA. - ME");
        sparseArray.append(1159, "Centrica Connected Home");
        sparseArray.append(1160, "Automotive Data Solutions Inc");
        sparseArray.append(1161, "Igarashi Engineering");
        sparseArray.append(1162, "Taelek Oy");
        sparseArray.append(1163, "CP Electronics Limited");
        sparseArray.append(1164, "Vectronix AG");
        sparseArray.append(1165, "S-Labs Sp. z o.o.");
        sparseArray.append(1166, "Companion Medical, Inc.");
        sparseArray.append(1167, "BlueKitchen GmbH");
        sparseArray.append(1168, "Matting AB");
        sparseArray.append(1169, "SOREX - Wireless Solutions GmbH");
        sparseArray.append(1170, "ADC Technology, Inc.");
        sparseArray.append(1171, "Lynxemi Pte Ltd");
        sparseArray.append(1172, "SENNHEISER electronic GmbH & Co. KG");
        sparseArray.append(1173, "LMT Mercer Group, Inc");
        sparseArray.append(1174, "Polymorphic Labs LLC");
        sparseArray.append(1175, "Cochlear Limited");
        sparseArray.append(1176, "METER Group, Inc. USA");
        sparseArray.append(1177, "Ruuvi Innovations Ltd.");
        sparseArray.append(1178, "Situne AS");
        sparseArray.append(1179, "nVisti,LLC");
        sparseArray.append(1180, "DyOcean");
        sparseArray.append(1181, "Uhlmann & Zacher GmbH");
        sparseArray.append(1182, "AND!XOR LLC");
        sparseArray.append(1183, "tictote AB");
        sparseArray.append(1184, "Vypin,LLC");
        sparseArray.append(1185, "PNI Sensor Corporation");
        sparseArray.append(1186, "ovrEngineered,LLC");
        sparseArray.append(1187, "GT-tronics HK Ltd");
        sparseArray.append(1188, "Herbert Waldmann GmbH & Co. KG");
        sparseArray.append(1189, "Guangzhou FiiO Electronics Technology Co.);Ltd");
        sparseArray.append(1190, "Vinetech Co.,Ltd");
        sparseArray.append(1191, "Dallas Logic Corporation");
        sparseArray.append(1192, "BioTex, Inc.");
        sparseArray.append(1193, "DISCOVERY SOUND TECHNOLOGY,LLC");
        sparseArray.append(1194, "LINKIO SAS");
        sparseArray.append(1195, "Harbortronics, Inc.");
        sparseArray.append(1196, "Undagrid B.V.");
        sparseArray.append(1197, "Shure Inc");
        sparseArray.append(1198, "ERM Electronic Systems LTD");
        sparseArray.append(1199, "BIOROWER Handelsagentur GmbH");
        sparseArray.append(1200, "Weba Sport und Med. Artikel GmbH");
        sparseArray.append(1201, "Kartographers Technologies Pvt. Ltd.");
        sparseArray.append(1202, "The Shadow on the Moon");
        sparseArray.append(1203, "mobike (Hong Kong,Limited");
        sparseArray.append(1204, "Inuheat Group AB");
        sparseArray.append(1205, "Swiftronix AB");
        sparseArray.append(1206, "Diagnoptics Technologies");
        sparseArray.append(1207, "Analog Devices, Inc.");
        sparseArray.append(1208, "Soraa Inc.");
        sparseArray.append(1209, "CSR Building Products Limited");
        sparseArray.append(1210, "Crestron Electronics, Inc.");
        sparseArray.append(1211, "Neatebox Ltd");
        sparseArray.append(1212, "Draegerwerk AG & Co. KGaA");
        sparseArray.append(1213, "AlbynMedical");
        sparseArray.append(1214, "Averos FZCO");
        sparseArray.append(1215, "VIT Initiative,LLC");
        sparseArray.append(1216, "Statsports International");
        sparseArray.append(1217, "Sospitas,s.r.o.");
        sparseArray.append(1218, "Dmet Products Corp.");
        sparseArray.append(1219, "Mantracourt Electronics Limited");
        sparseArray.append(1220, "TeAM Hutchins AB");
        sparseArray.append(1221, "Seibert Williams Glass,LLC");
        sparseArray.append(1222, "Insta GmbH");
        sparseArray.append(1223, "Svantek Sp. z o.o.");
        sparseArray.append(1224, "Shanghai Flyco Electrical Appliance Co.,Ltd.");
        sparseArray.append(1225, "Thornwave Labs Inc");
        sparseArray.append(1226, "Steiner-Optik GmbH");
        sparseArray.append(1227, "Novo Nordisk A/S");
        sparseArray.append(1228, "Enflux Inc.");
        sparseArray.append(1229, "Safetech Products LLC");
        sparseArray.append(1230, "GOOOLED S.R.L.");
        sparseArray.append(1231, "DOM Sicherheitstechnik GmbH & Co. KG");
        sparseArray.append(1232, "Olympus Corporation");
        sparseArray.append(1233, "KTS GmbH");
        sparseArray.append(1234, "Anloq Technologies Inc.");
        sparseArray.append(1235, "Queercon, Inc");
        sparseArray.append(1236, "5th Element Ltd");
        sparseArray.append(1237, "Gooee Limited");
        sparseArray.append(1238, "LUGLOC LLC");
        sparseArray.append(1239, "Blincam, Inc.");
        sparseArray.append(1240, "FUJIFILM Corporation");
        sparseArray.append(1241, "RandMcNally");
        sparseArray.append(1242, "Franceschi Marina snc");
        sparseArray.append(1243, "Engineered Audio,LLC.");
        sparseArray.append(1244, "IOTTIVE (OPC,PRIVATE LIMITED");
        sparseArray.append(1245, "4MOD Technology");
        sparseArray.append(1246, "Lutron Electronics Co., Inc.");
        sparseArray.append(1247, "Emerson");
        sparseArray.append(1248, "Guardtec, Inc.");
        sparseArray.append(1249, "REACTEC LIMITED");
        sparseArray.append(1250, "EllieGrid");
        sparseArray.append(1251, "Under Armour");
        sparseArray.append(1252, "Woodenshark");
        sparseArray.append(1253, "Avack Oy");
        sparseArray.append(1254, "Smart Solution Technology, Inc.");
        sparseArray.append(1255, "REHABTRONICS INC.");
        sparseArray.append(1256, "STABILO International");
        sparseArray.append(1257, "Busch Jaeger Elektro GmbH");
        sparseArray.append(1258, "Pacific Bioscience Laboratories, Inc");
        sparseArray.append(1259, "Bird Home Automation GmbH");
        sparseArray.append(1260, "Motorola Solutions");
        sparseArray.append(1261, "R9 Technology, Inc.");
        sparseArray.append(1262, "Auxivia");
        sparseArray.append(1263, "DaisyWorks, Inc");
        sparseArray.append(1264, "Kosi Limited");
        sparseArray.append(1265, "Theben AG");
        sparseArray.append(1266, "InDreamer Techsol Private Limited");
        sparseArray.append(1267, "Cerevast Medical");
        sparseArray.append(1268, "ZanCompute Inc.");
        sparseArray.append(1269, "Pirelli Tyre S.P.A.");
        sparseArray.append(1270, "McLear Limited");
        sparseArray.append(1271, "Shenzhen Huiding Technology Co.);Ltd.");
        sparseArray.append(1272, "Convergence Systems Limited");
        sparseArray.append(1273, "Interactio");
        sparseArray.append(1274, "Androtec GmbH");
        sparseArray.append(1275, "Benchmark Drives GmbH & Co. KG");
        sparseArray.append(1276, "SwingLync L. L. C.");
        sparseArray.append(1277, "Tapkey GmbH");
        sparseArray.append(1278, "Woosim Systems Inc.");
        sparseArray.append(AdaptiveTrackSelection.DEFAULT_MAX_WIDTH_TO_DISCARD, "Microsemi Corporation");
        sparseArray.append(PlatformPlugin.DEFAULT_SYSTEM_UI, "Wiliot LTD.");
        sparseArray.append(1281, "Polaris IND");
        sparseArray.append(1282, "Specifi-Kali LLC");
        sparseArray.append(1283, "Locoroll, Inc");
        sparseArray.append(1284, "PHYPLUS Inc");
        sparseArray.append(1285, "Inplay Technologies LLC");
        sparseArray.append(1286, "Hager");
        sparseArray.append(1287, "Yellowcog");
        sparseArray.append(1288, "Axes System sp. z o. o.");
        sparseArray.append(1289, "myLIFTER Inc.");
        sparseArray.append(1290, "Shake-on B.V.");
        sparseArray.append(1291, "Vibrissa Inc.");
        sparseArray.append(1292, "OSRAM GmbH");
        sparseArray.append(1293, "TRSystems GmbH");
        sparseArray.append(1294, "Yichip Microelectronics (Hangzhou,Co.);Ltd.");
        sparseArray.append(1295, "Foundation Engineering LLC");
        sparseArray.append(1296, "UNI-ELECTRONICS, Inc.");
        sparseArray.append(1297, "Brookfield Equinox LLC");
        sparseArray.append(1298, "Soprod SA");
        sparseArray.append(1299, "9974091 Canada Inc.");
        sparseArray.append(1300, "FIBRO GmbH");
        sparseArray.append(1301, "RB Controls Co.,Ltd.");
        sparseArray.append(1302, "Footmarks");
        sparseArray.append(1303, "Amcore AB");
        sparseArray.append(1304, "MAMORIO.inc");
        sparseArray.append(1305, "Tyto Life LLC");
        sparseArray.append(1306, "Leica Camera AG");
        sparseArray.append(1307, "Angee Technologies Ltd.");
        sparseArray.append(1308, "EDPS");
        sparseArray.append(1309, "OFF Line Co.,Ltd.");
        sparseArray.append(1310, "Detect Blue Limited");
        sparseArray.append(1311, "Setec Pty Ltd");
        sparseArray.append(1312, "Target Corporation");
        sparseArray.append(1313, "IAI Corporation");
        sparseArray.append(1314, "NS Tech, Inc.");
        sparseArray.append(1315, "MTG Co.,Ltd.");
        sparseArray.append(1316, "Hangzhou iMagic Technology Co.,Ltd");
        sparseArray.append(1317, "HONGKONG NANO IC TECHNOLOGIES CO.,LIMITED");
        sparseArray.append(1318, "Honeywell International Inc.");
        sparseArray.append(1319, "Albrecht JUNG");
        sparseArray.append(1320, "Lunera Lighting Inc.");
        sparseArray.append(1321, "Lumen UAB");
        sparseArray.append(1322, "Keynes Controls Ltd");
        sparseArray.append(1323, "Novartis AG");
        sparseArray.append(1324, "Geosatis SA");
        sparseArray.append(1325, "EXFO, Inc.");
        sparseArray.append(1326, "LEDVANCE GmbH");
        sparseArray.append(1327, "Center ID Corp.");
        sparseArray.append(1328, "Adolene, Inc.");
        sparseArray.append(1329, "D&M Holdings Inc.");
        sparseArray.append(1330, "CRESCO Wireless, Inc.");
        sparseArray.append(1331, "Nura Operations Pty Ltd");
        sparseArray.append(1332, "Frontiergadget, Inc.");
        sparseArray.append(1333, "Smart Component Technologies Limited");
        sparseArray.append(1334, "ZTR Control Systems LLC");
        sparseArray.append(1335, "MetaLogics Corporation");
        sparseArray.append(1336, "Medela AG");
        sparseArray.append(1337, "OPPLE Lighting Co.,Ltd");
        sparseArray.append(1338, "Savitech Corp.);");
        sparseArray.append(1339, "prodigy");
        sparseArray.append(1340, "Screenovate Technologies Ltd");
        sparseArray.append(1341, "TESA SA");
        sparseArray.append(1342, "CLIM8 LIMITED");
        sparseArray.append(1343, "Silergy Corp");
        sparseArray.append(1344, "SilverPlus, Inc");
        sparseArray.append(1345, "Sharknet srl");
        sparseArray.append(1346, "Mist Systems, Inc.");
        sparseArray.append(1347, "MIWA LOCK CO.);Ltd");
        sparseArray.append(1348, "OrthoSensor, Inc.");
        sparseArray.append(1349, "Candy Hoover Group s.r.l");
        sparseArray.append(1350, "Apexar Technologies S.A.");
        sparseArray.append(1351, "LOGICDATA d.o.o.");
        sparseArray.append(1352, "Knick Elektronische Messgeraete GmbH & Co. KG");
        sparseArray.append(1353, "Smart Technologies and Investment Limited");
        sparseArray.append(1354, "Linough Inc.");
        sparseArray.append(1355, "Advanced Electronic Designs, Inc.");
        sparseArray.append(1356, "Carefree Scott Fetzer Co Inc");
        sparseArray.append(1357, "Sensome");
        sparseArray.append(1358, "FORTRONIK storitve d.o.o.");
        sparseArray.append(1359, "Sinnoz");
        sparseArray.append(1360, "Versa Networks, Inc.");
        sparseArray.append(1361, "Sylero");
        sparseArray.append(1362, "Avempace SARL");
        sparseArray.append(1363, "Nintendo Co.,Ltd.");
        sparseArray.append(1364, "National Instruments");
        sparseArray.append(1365, "KROHNE Messtechnik GmbH");
        sparseArray.append(1366, "Otodynamics Ltd");
        sparseArray.append(1367, "Arwin Technology Limited");
        sparseArray.append(1368, "benegear, Inc.");
        sparseArray.append(1369, "Newcon Optik");
        sparseArray.append(1370, "CANDY HOUSE, Inc.");
        sparseArray.append(1371, "FRANKLIN TECHNOLOGY INC");
        sparseArray.append(1372, "Lely");
        sparseArray.append(1373, "Valve Corporation");
        sparseArray.append(1374, "Hekatron Vertriebs GmbH");
        sparseArray.append(1375, "PROTECH S.A.S. DI GIRARDI ANDREA & C.");
        sparseArray.append(1376, "Sarita CareTech IVS");
        sparseArray.append(1377, "Finder S.p.A.");
        sparseArray.append(1378, "Thalmic Labs Inc.");
        sparseArray.append(1379, "Steinel Vertrieb GmbH");
        sparseArray.append(1380, "Beghelli Spa");
        sparseArray.append(1381, "Beijing Smartspace Technologies Inc.");
        sparseArray.append(1382, "CORE TRANSPORT TECHNOLOGIES NZ LIMITED");
        sparseArray.append(1383, "Xiamen Everesports Goods Co.,Ltd");
        sparseArray.append(1384, "Bodyport Inc.");
        sparseArray.append(1385, "Audionics System, Inc.");
        sparseArray.append(1386, "Flipnavi Co.);Ltd.");
        sparseArray.append(1387, "Rion Co.,Ltd.");
        sparseArray.append(1388, "Long Range Systems,LLC");
        sparseArray.append(1389, "Redmond Industrial Group LLC");
        sparseArray.append(1390, "VIZPIN INC.");
        sparseArray.append(1391, "BikeFinder AS");
        sparseArray.append(1392, "Consumer Sleep Solutions LLC");
        sparseArray.append(1393, "PSIKICK, Inc.");
        sparseArray.append(1394, "AntTail.com");
        sparseArray.append(1395, "Lighting Science Group Corp.");
        sparseArray.append(1396, "AFFORDABLE ELECTRONICS INC");
        sparseArray.append(1397, "Integral Memroy Plc");
        sparseArray.append(1398, "Globalstar, Inc.");
        sparseArray.append(1399, "True Wearables, Inc.");
        sparseArray.append(1400, "Wellington Drive Technologies Ltd");
        sparseArray.append(1401, "Ensemble Tech Private Limited");
        sparseArray.append(1402, "OMNI Remotes");
        sparseArray.append(1403, "Duracell U.S. Operations Inc.");
        sparseArray.append(1404, "Toor Technologies LLC");
        sparseArray.append(1405, "Instinct Performance");
        sparseArray.append(1406, "Beco, Inc");
        sparseArray.append(1407, "Scuf Gaming International,LLC");
        sparseArray.append(1408, "ARANZ Medical Limited");
        sparseArray.append(1409, "LYS TECHNOLOGIES LTD");
        sparseArray.append(1410, "Breakwall Analytics,LLC");
        sparseArray.append(1411, "Code Blue Communications");
        sparseArray.append(1412, "Gira Giersiepen GmbH & Co. KG");
        sparseArray.append(1413, "Hearing Lab Technology");
        sparseArray.append(1414, "LEGRAND");
        sparseArray.append(1415, "Derichs GmbH");
        sparseArray.append(1416, "ALT-TEKNIK LLC");
        sparseArray.append(1417, "Star Technologies");
        sparseArray.append(1418, "START TODAY CO.);LTD.");
        sparseArray.append(1419, "Maxim Integrated Products");
        sparseArray.append(1420, "MERCK Kommanditgesellschaft auf Aktien");
        sparseArray.append(1421, "Jungheinrich Aktiengesellschaft");
        sparseArray.append(1422, "Oculus VR,LLC");
        sparseArray.append(1423, "HENDON SEMICONDUCTORS PTY LTD");
        sparseArray.append(1424, "Pur3 Ltd");
        sparseArray.append(1425, "Viasat Group S.p.A.");
        sparseArray.append(1426, "IZITHERM");
        sparseArray.append(1427, "Spaulding Clinical Research");
        sparseArray.append(1428, "Kohler Company");
        sparseArray.append(1429, "Inor Process AB");
        sparseArray.append(1430, "My Smart Blinds");
        sparseArray.append(1431, "RadioPulse Inc");
        sparseArray.append(1432, "rapitag GmbH");
        sparseArray.append(1433, "Lazlo326,LLC.");
        sparseArray.append(1434, "Teledyne Lecroy, Inc.");
        sparseArray.append(1435, "Dataflow Systems Limited");
        sparseArray.append(1436, "Macrogiga Electronics");
        sparseArray.append(1437, "Tandem Diabetes Care");
        sparseArray.append(1438, "Polycom, Inc.");
        sparseArray.append(1439, "Fisher & Paykel Healthcare");
        sparseArray.append(DateTimeConstants.MINUTES_PER_DAY, "RCP Software Oy");
        sparseArray.append(1441, "Shanghai Xiaoyi Technology Co.);Ltd.");
        sparseArray.append(1442, "ADHERIUM(NZ,LIMITED");
        sparseArray.append(1443, "Axiomware Systems Incorporated");
        sparseArray.append(1444, "O. E. M. Controls, Inc.");
        sparseArray.append(1445, "Kiiroo BV");
        sparseArray.append(1446, "Telecon Mobile Limited");
        sparseArray.append(1447, "Sonos Inc");
        sparseArray.append(1448, "Tom Allebrandi Consulting");
        sparseArray.append(1449, "Monidor");
        sparseArray.append(1450, "Tramex Limited");
        sparseArray.append(1451, "Nofence AS");
        sparseArray.append(1452, "GoerTek Dynaudio Co.,Ltd.");
        sparseArray.append(1453, "INIA");
        sparseArray.append(1454, "CARMATE MFG.CO.);LTD");
        sparseArray.append(1455, "ONvocal");
        sparseArray.append(1456, "NewTec GmbH");
        sparseArray.append(1457, "Medallion Instrumentation Systems");
        sparseArray.append(1458, "CAREL INDUSTRIES S.P.A.");
        sparseArray.append(1459, "Parabit Systems, Inc.");
        sparseArray.append(DNSConstants.MAX_MSG_TYPICAL, "White Horse Scientific ltd");
        sparseArray.append(1461, "verisilicon");
        sparseArray.append(1462, "Elecs Industry Co.);Ltd.");
        sparseArray.append(1463, "Beijing Pinecone Electronics Co.);Ltd.");
        sparseArray.append(1464, "Ambystoma Labs Inc.");
        sparseArray.append(1465, "Suzhou Pairlink Network Technology");
        sparseArray.append(1466, "igloohome");
        sparseArray.append(1467, "Oxford Metrics plc");
        sparseArray.append(1468, "Leviton Mfg. Co., Inc.");
        sparseArray.append(1469, "ULC Robotics Inc.");
        sparseArray.append(1470, "RFID Global by Softwork SrL");
        sparseArray.append(1471, "Real-World-Systems Corporation");
        sparseArray.append(1472, "Nalu Medical, Inc.");
        sparseArray.append(1473, "P.I.Engineering");
        sparseArray.append(1474, "Grote Industries");
        sparseArray.append(1475, "Runtime, Inc.");
        sparseArray.append(1476, "Codecoup sp. z o.o. sp. k.");
        sparseArray.append(1477, "SELVE GmbH & Co. KG");
        sparseArray.append(1478, "Smart Animal Training Systems,LLC");
        sparseArray.append(1479, "Lippert Components, Inc");
        sparseArray.append(1480, "SOMFY SAS");
        sparseArray.append(1481, "TBS Electronics B.V.");
        sparseArray.append(1482, "MHL Custom Inc");
        sparseArray.append(1483, "LucentWear LLC");
        sparseArray.append(1484, "WATTS ELECTRONICS");
        sparseArray.append(1485, "RJ Brands LLC");
        sparseArray.append(1486, "V-ZUG Ltd");
        sparseArray.append(1487, "Biowatch SA");
        sparseArray.append(1488, "Anova Applied Electronics");
        sparseArray.append(1489, "Lindab AB");
        sparseArray.append(1490, "frogblue TECHNOLOGY GmbH");
        sparseArray.append(1491, "Acurable Limited");
        sparseArray.append(1492, "LAMPLIGHT Co.,Ltd.");
        sparseArray.append(1493, "TEGAM, Inc.");
        sparseArray.append(1494, "Zhuhai Jieli technology Co.);Ltd");
        sparseArray.append(1495, "modum.io AG");
        sparseArray.append(1496, "Farm Jenny LLC");
        sparseArray.append(1497, "Toyo Electronics Corporation");
        sparseArray.append(1498, "Applied Neural Research Corp");
        sparseArray.append(1499, "Avid Identification Systems, Inc.");
        sparseArray.append(ConnectionResult.DRIVE_EXTERNAL_STORAGE_REQUIRED, "Petronics Inc.");
        sparseArray.append(1501, "essentim GmbH");
        sparseArray.append(1502, "QT Medical INC.");
        sparseArray.append(1503, "VIRTUALCLINIC.DIRECT LIMITED");
        sparseArray.append(1504, "Viper Design LLC");
        sparseArray.append(1505, "Human, Incorporated");
        sparseArray.append(1506, "stAPPtronics GmbH");
        sparseArray.append(1507, "Elemental Machines, Inc.");
        sparseArray.append(1508, "Taiyo Yuden Co.,Ltd");
        sparseArray.append(1509, "INEO ENERGY& SYSTEMS");
        sparseArray.append(1510, "Motion Instruments Inc.");
        sparseArray.append(1511, "PressurePro");
        sparseArray.append(1512, "COWBOY");
        sparseArray.append(1513, "iconmobile GmbH");
        sparseArray.append(1514, "ACS-Control-System GmbH");
        sparseArray.append(1515, "Bayerische Motoren Werke AG");
        sparseArray.append(1516, "Gycom Svenska AB");
        sparseArray.append(1517, "Fuji Xerox Co.,Ltd");
        sparseArray.append(1518, "Glide Inc.");
        sparseArray.append(1519, "SIKOM AS");
        sparseArray.append(1520, "beken");
        sparseArray.append(1521, "The Linux Foundation");
        sparseArray.append(1522, "Try and E CO.);LTD.");
        sparseArray.append(1523, "SeeScan");
        sparseArray.append(1524, "Clearity,LLC");
        sparseArray.append(1525, "GS TAG");
        sparseArray.append(1526, "DPTechnics");
        sparseArray.append(1527, "TRACMO, Inc.");
        sparseArray.append(1528, "Anki Inc.");
        sparseArray.append(1529, "Hagleitner Hygiene International GmbH");
        sparseArray.append(1530, "Konami Sports Life Co.,Ltd.");
        sparseArray.append(1531, "Arblet Inc.");
        sparseArray.append(1532, "Masbando GmbH");
        sparseArray.append(1533, "Innoseis");
        sparseArray.append(1534, "Niko");
        sparseArray.append(1535, "Wellnomics Ltd");
        sparseArray.append(1536, "iRobot Corporation");
        sparseArray.append(1537, "Schrader Electronics");
        sparseArray.append(1538, "Geberit International AG");
        sparseArray.append(1539, "Fourth Evolution Inc");
        sparseArray.append(1540, "Cell2Jack LLC");
        sparseArray.append(1541, "FMW electronic Futterer u. Maier-Wolf OHG");
        sparseArray.append(1542, "John Deere");
        sparseArray.append(1543, "Rookery Technology Ltd");
        sparseArray.append(1544, "KeySafe-Cloud");
        sparseArray.append(1545, "Bchi Labortechnik AG");
        sparseArray.append(1546, "IQAir AG");
        sparseArray.append(1547, "Triax Technologies Inc");
        sparseArray.append(1548, "Vuzix Corporation");
        sparseArray.append(1549, "TDK Corporation");
        sparseArray.append(1550, "Blueair AB");
        sparseArray.append(1551, "Philips Lighting B.V.");
        sparseArray.append(1552, "ADH GUARDIAN USA LLC");
        sparseArray.append(1553, "Beurer GmbH");
        sparseArray.append(1554, "Playfinity AS");
        sparseArray.append(1555, "Hans Dinslage GmbH");
        sparseArray.append(1556, "OnAsset Intelligence, Inc.");
        sparseArray.append(1557, "INTER ACTION Corporation");
        sparseArray.append(1558, "OS42 UG (haftungsbeschraenkt);");
        sparseArray.append(1559, "WIZCONNECTED COMPANY LIMITED");
        sparseArray.append(1560, "Audio-Technica Corporation");
    }
}
